import Link from 'next/link';
import {ArrowUpRight,Check} from 'lucide-react';

export const metadata={title:'Marketing Consulting Services',description:'Strategy, growth, positioning, B2B demand, product marketing, GTM, CRM and fractional marketing advisory for founders and business leaders.',keywords:['marketing consultant India','marketing consultant Bangalore','B2B marketing consultant','growth marketing consultant','brand positioning consultant','product marketing consultant','GTM consultant','fractional marketing consultant']};

const services=[
 {id:'quick',eyebrow:'Start here',title:'Fix one important thing',copy:'A focused intervention when you already know something is wrong but want an experienced diagnosis before spending months fixing it.',items:['Landing page and funnel diagnosis','Positioning and messaging review','Growth problem diagnosis','Founder or leadership strategy session'],out:'A clear diagnosis, prioritised actions and a practical next step.'},
 {id:'strategy',eyebrow:'Project',title:'Build the marketing system',copy:'A strategy project for businesses that need clearer choices across customer, positioning, demand, channels, product marketing or lifecycle.',items:['Marketing and growth strategy','B2B demand generation','Product marketing and GTM','Brand positioning','CRM and lifecycle strategy'],out:'A decision-ready strategy, operating priorities and a plan your team can actually execute.'},
 {id:'advisory',eyebrow:'Ongoing',title:'Senior marketing in the room',copy:'Fractional advisory for founders and teams that need senior judgement, prioritisation and hands-on problem solving without immediately hiring a full-time leader.',items:['Weekly leadership input','Growth and marketing prioritisation','Team and agency direction','Performance and commercial reviews','Hands-on problem solving'],out:'An experienced marketing partner focused on the business problem, not a generic retainer checklist.'}
];

export default function Services(){return <main className="surface-pearl commercial-page"><section className="commercial-hero"><div className="container"><p className="label">Services</p><h1 className="display h-xl">I do not sell marketing packages.<br/><span>I solve marketing problems.</span></h1><p className="commercial-lead">Bring me the business problem first. We work out what is actually stuck, what evidence we have, and what kind of intervention makes sense.</p></div></section><section className="container service-detail-list">{services.map((s,i)=><article id={s.id} className={`service-detail ${i===2?'dark-service':''}`} key={s.id}><div><p className="eyebrow">{s.eyebrow}</p><h2 className="display h-lg">{s.title}</h2><p className="service-copy">{s.copy}</p></div><div><p className="service-label">What this can include</p><ul>{s.items.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><p className="service-label">What you leave with</p><p>{s.out}</p><Link className="button" href="/#booking">Talk about the problem <ArrowUpRight size={16}/></Link></div></article>)}</section><section className="surface-ink commercial-close"><div className="container commercial-close-inner"><div><p className="label">The rule</p><h2 className="display h-lg">No channel shopping before diagnosis.</h2></div><div><p>I will not recommend SEO because you mentioned SEO, or paid media because you have budget. The recommendation should follow the commercial constraint, customer behaviour and evidence.</p><Link className="button" href="/#booking">Tell me what is stuck <ArrowUpRight size={16}/></Link></div></div></section></main>}
