import Link from 'next/link';
import { ArrowUpRight, CalendarDays, CheckCircle2 } from 'lucide-react';

export const metadata={title:'Marketing Consulting Services | Siddharth Bhattacharjee',description:'Marketing consulting for B2B and B2C businesses: strategy, growth, positioning, product marketing, GTM, CRM, SEO and fractional advisory.'};

const projects=[
 {id:'01',title:'Marketing strategy',desc:'For businesses that need clearer priorities, sharper positioning and a plan the team can actually execute.',items:['Business and customer diagnosis','Audience and positioning strategy','Channel and growth priorities','90-day roadmap']},
 {id:'02',title:'B2B marketing',desc:'For businesses that need a more repeatable way to create demand, generate qualified leads and turn expertise into growth.',items:['B2B positioning','Demand and acquisition strategy','Content and SEO direction','Lead-to-revenue funnel']},
 {id:'03',title:'B2C & ecommerce marketing',desc:'For consumer businesses that need better acquisition, conversion, retention or customer economics.',items:['Customer acquisition strategy','Conversion optimisation','Lifecycle and retention','Growth experiments']},
 {id:'04',title:'Product marketing & GTM',desc:'For new products, launches and businesses that need customers to understand the value before they can buy it.',items:['Product positioning','Messaging and value proposition','Launch and GTM plan','Adoption and activation']},
 {id:'05',title:'Brand & positioning',desc:'For businesses that sound like everyone else and need a clearer reason for customers to choose them.',items:['Category and competitor review','Positioning territory','Messaging architecture','Brand point of view']},
 {id:'06',title:'CRM & retention',desc:'For businesses that already have customers but are leaving repeat value on the table.',items:['Customer lifecycle mapping','Segmentation','Lifecycle communication','Retention experiments']},
];
const quick=[
 ['Landing page conversion review','I review the proposition, hierarchy, proof, objections and CTA flow, then give you a prioritised teardown.'],
 ['Marketing funnel teardown','A focused review of where prospects drop between attention, consideration, enquiry and purchase.'],
 ['Positioning & messaging review','Pressure-test what you say, who you say it to and whether the message gives people a reason to choose you.'],
 ['90-minute founder strategy session','Bring one messy marketing problem. Leave with a diagnosis, priorities and next steps.'],
 ['GTM sanity check','Pressure-test your launch audience, proposition, channels, sequencing and measurement before you spend.'],
 ['SEO content audit','Find content gaps, weak pages and the topics that could build genuine search authority.'],
];
export default function Services(){return <main>
<section className="container services-hero"><div className="eyebrow">Marketing consulting · B2B · B2C</div><h1 className="display">You bring the business problem.<br/><span>I help work out what marketing should do about it.</span></h1><p>I work with founders, business owners and marketing teams on strategy, growth, positioning, acquisition, product marketing, GTM, CRM, SEO and ongoing marketing leadership.</p><div className="actions"><a className="button" href="/#booking">Tell me what&apos;s stuck <ArrowUpRight size={16}/></a><Link className="button alt" href="/#problems">See the problems I solve</Link></div></section>
<section className="container section" id="quick"><div className="section-head"><h2 className="display">Start small<br/>if you want.</h2><p>You do not need a six-week project to get value from an experienced marketer. These are focused engagements designed around one important problem.</p></div><div className="quick-grid light-quick">{quick.map(([title,desc],i)=><article className="quick-card light" key={title}><div className="num">0{i+1} · Focused service</div><h3>{title}</h3><p>{desc}</p><a href="/#booking">Start with this <ArrowUpRight size={15}/></a></article>)}</div></section>
<section className="container section" id="strategy"><div className="section-head"><h2 className="display">Larger problems<br/>need a system.</h2><p>These are the engagements where I work deeper into the business and help turn a messy marketing function into a clearer operating plan.</p></div><div className="services-page-grid">{projects.map(s=><article className="service-card large" key={s.id}><div className="num">{s.id}</div><h2>{s.title}</h2><p>{s.desc}</p><div className="mini-services">{s.items.map(x=><span key={x}><CheckCircle2 size={14}/>{x}</span>)}</div></article>)}</div></section>
<section className="dark-section section" id="advisory"><div className="container"><div className="section-head"><h2 className="display">Need someone<br/>in the room?</h2><p>Fractional marketing advisory gives founders and teams access to senior marketing thinking without immediately hiring a full-time leader.</p></div><div className="advisory-grid"><div><div className="num">What I can do</div><ul className="big-list"><li>Challenge the current marketing strategy</li><li>Prioritise the team&apos;s roadmap</li><li>Review agencies, campaigns and channels</li><li>Help founders make difficult marketing decisions</li><li>Work with product, sales and leadership teams</li><li>Build a practical marketing operating rhythm</li></ul></div><div className="advisory-card"><div className="eyebrow">Best when</div><h3>You have people doing marketing, but need someone experienced to connect the dots.</h3><p>This can be a short-term intervention around a major business problem or an ongoing advisory relationship.</p><a className="button" href="/#booking">Discuss advisory <ArrowUpRight size={16}/></a></div></div></div></section>
<section className="container section services-fit"><div><div className="eyebrow">Who this is for</div><h2 className="display">B2B or B2C.<br/>The problem comes first.</h2></div><div className="fit-list"><div><strong>Business owners & founders</strong><span>You need clarity on what marketing should do next, without hiring a full team to figure it out.</span></div><div><strong>Growing B2B businesses</strong><span>You want to move beyond referrals and build a more repeatable demand and lead-generation system.</span></div><div><strong>Consumer & ecommerce businesses</strong><span>You need better acquisition, conversion, retention or customer economics.</span></div><div><strong>Marketing teams</strong><span>You want an experienced outside perspective on strategy, prioritisation, positioning or growth.</span></div></div></section>
<section className="container cta"><div className="cta-box"><div><div className="eyebrow">Not sure what you need?</div><h2>Start with the problem, not the service.</h2></div><div><p>Send a short brief. I&apos;ll help you figure out whether the right answer is a quick review, a strategy project, ongoing advisory or simply a useful conversation.</p><a className="button" href="/#booking">Send a brief <ArrowUpRight size={16}/></a></div></div></section>
</main>}
