import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import {caseStudies} from '../../lib/case-studies';

export const metadata={title:'Marketing Proof of Work',description:'First-hand marketing work from Amazon and selected illustrative strategy cases showing how Siddharth Bhattacharjee diagnoses growth, lifecycle, product marketing, brand and demand problems.'};

function Card({c}:{c:(typeof caseStudies)[number]}){return <Link className="case-card" href={`/case-studies/${c.slug}`}><div><span className="eyebrow">{c.category}</span><span className="case-type">{c.type==='Illustrative strategy'?'Illustrative':'First-hand'}</span></div><h2>{c.title}</h2><p>{c.summary}</p><strong>{c.proof}</strong><span className="meta">Read the case <ArrowUpRight size={15}/></span></Link>}

export default function CaseStudies(){const experience=caseStudies.filter(c=>c.type==='Siddharth experience');const illustrative=caseStudies.filter(c=>c.type==='Illustrative strategy');return <main className="surface-pearl commercial-page"><section className="commercial-hero"><div className="container"><p className="label">Proof of work</p><h1 className="display h-xl">Show the work.<br/><span>Then show the thinking.</span></h1><p className="commercial-lead">A marketing portfolio should do more than list responsibilities. These cases unpack the business problem, diagnosis, decisions, measurement and outcome. First-hand work is clearly separated from illustrative strategy.</p></div></section><section className="container case-section"><div className="case-section-head"><div><p className="eyebrow">First-hand experience</p><h2 className="display h-lg">Work I actually did.</h2></div><p>These cases are based on my professional experience across Amazon Pay, Amazon MX Player, marketplace brand management and B2B technology marketing. Where an exact commercial result is not public or not defensible from the available record, I say so.</p></div><div className="case-grid">{experience.map(c=><Card c={c} key={c.slug}/>)}</div></section><section className="container case-section"><div className="case-section-head"><div><p className="eyebrow">Illustrative strategy</p><h2 className="display h-lg">How I would solve it.</h2></div><p>These are not client projects. The companies, data and outcomes are hypothetical. They exist to demonstrate how I would diagnose a marketing problem, build a strategy and decide what to measure.</p></div><div className="case-grid">{illustrative.map(c=><Card c={c} key={c.slug}/>)}</div></section><section className="surface-ink commercial-close"><div className="container commercial-close-inner"><div><p className="label">Bring your problem</p><h2 className="display h-lg">The next case study could be yours.</h2></div><div><p>If the business problem looks familiar, I would rather diagnose it with you than sell you a package before understanding it.</p><Link className="button" href="/#booking">Talk about your business <ArrowUpRight size={16}/></Link></div></div></section></main>}
