import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, CalendarDays } from 'lucide-react';
import Problems from '../components/Problems';

const proof = [['11+ years','Across B2B and B2C marketing'],['200M+','Customers reached through programs'],['+173%','Streamer DAU growth in one program']];
const fit = [['B2B business','You need more qualified demand, a clearer proposition, or less dependence on referrals.'],['Consumer business','You need better acquisition, conversion, repeat purchase or customer economics.'],['Product or startup','You need positioning, GTM, launch or growth decisions that connect to the business goal.']];
const articles = [['Marketing Strategy','How to build a marketing strategy that actually drives growth','A practical framework for turning a business goal into clear marketing choices.','/blog/how-to-build-a-marketing-strategy'],['B2B Marketing','B2B marketing strategy: where to start when referrals do all the work','How to build a more repeatable demand engine.','/blog/b2b-marketing-strategy'],['Growth','Landing page conversion: the 12 things I check first','A practical review before you spend more money driving traffic.','/blog/landing-page-conversion-checklist'],['Positioning','Why good businesses still struggle to explain what they do','Find the gap between what you sell and what customers understand.','/blog/why-good-businesses-struggle-to-explain-what-they-do']];

export default function Home(){return <main>
<section className="container home-hero"><div className="hero-copy"><div className="eyebrow">Marketing consultant · B2B · B2C</div><h1 className="display">What&apos;s getting in the way of growth?</h1><p>If your marketing is generating activity but not enough business, your pipeline is too dependent on referrals, or your team is busy without a clear direction, start with the problem. I help find what is getting in the way and what to fix first.</p><div className="actions"><a className="button" href="#problems">Find your problem <ArrowUpRight size={16}/></a><a className="button alt" href="#booking">Book a conversation</a></div><div className="proof-row">{proof.map(([value,label])=><div key={value}><strong>{value}</strong><span>{label}</span></div>)}</div></div><div className="hero-image"><div className="portrait-frame"><Image src="/siddharth-bhattacharjee.jpg" alt="Siddharth Bhattacharjee, marketing consultant" width={848} height={1264} priority className="portrait"/><div className="portrait-label"><span>SIDDHARTH BHATTACHARJEE</span><span>MARKETING / GROWTH / STRATEGY</span></div></div><div className="hero-note"><b>Need a quick answer?</b><span>Landing page reviews, positioning reviews, funnel teardowns and strategy sessions.</span></div></div></section>
<section className="section diagnostic-section" id="problems"><div className="container"><div className="section-head"><div><div className="eyebrow">START WITH THE PROBLEM</div><h2 className="display">Tell me what&apos;s<br/>not working.</h2></div><p>Pick the situation closest to yours. I&apos;ll show you how I would diagnose it, what I would look at first and what the work could produce.</p></div><Problems/></div></section>
<section className="section dark-section" id="fit"><div className="container"><div className="section-head"><div><div className="eyebrow">WHERE I CAN HELP</div><h2 className="display">Your business first.<br/>Marketing second.</h2></div><p>I don&apos;t start by selling a marketing channel. I start by understanding what the business needs to change.</p></div><div className="fit-grid">{fit.map(([title,text],i)=><div className="fit-card" key={title}><span className="num">0{i+1}</span><h3>{title}</h3><p>{text}</p><Link href="/services">See how I can help <ArrowUpRight size={15}/></Link></div>)}</div><div className="experience-line"><span>Relevant experience</span><b>B2B technology</b><b>Fintech</b><b>Commerce</b><b>Entertainment</b><b>Consumer products</b><b>Product marketing</b></div></div></section>
<section className="section book-section" id="book"><div className="container book-feature"><div className="book-cover"><div className="book-small">SIDDHARTH BHATTACHARJEE</div><div className="book-title">SOVEREIGN<br/>BRAND</div><div className="book-rule"></div><div className="book-sub">The AI Marketing Playbook for the Ambitious Professional</div></div><div className="book-copy"><div className="eyebrow">THE BOOK</div><h2 className="display">A practical point of view on marketing in an AI-first world.</h2><p><i>The Sovereign Brand: The AI Marketing Playbook for the Ambitious Professional</i> is my take on building a stronger marketing point of view when AI is changing how marketers work.</p><div className="book-actions"><a className="button" href="https://www.amazon.in/Sovereign-Brand-Marketing-Ambitious-Professional-ebook/dp/B0H1CPMBLN" target="_blank" rel="noreferrer">Get the e-book <ArrowUpRight size={16}/></a><a className="button alt" href="https://siddster14.gumroad.com/l/the-sovereign-brand" target="_blank" rel="noreferrer">Get the book <ArrowUpRight size={16}/></a></div><Link className="text-link" href="/book">Read about the book <ArrowUpRight size={15}/></Link></div></div></section>
<section className="section insights-section" id="insights"><div className="container"><div className="section-head"><div><div className="eyebrow">THE MARKETING BRIEF</div><h2 className="display">Useful thinking.<br/>No marketing theatre.</h2></div><p>Practical articles for founders, business owners and marketing teams. Start with the problem you are trying to solve.</p></div><div className="article-grid">{articles.map(([category,title,excerpt,href],i)=><Link className={`article-card ${i===0?'article-featured':''}`} href={href} key={title}><span className="num">{category}</span><h3>{title}</h3><p>{excerpt}</p><span className="read-link">Read article <ArrowUpRight size={14}/></span></Link>)}</div><div className="section-bottom"><Link href="/blog">See all articles <ArrowUpRight size={15}/></Link><span>New practical marketing ideas every week</span></div></div></section>
<section className="section cta-section" id="booking"><div className="container cta-layout"><div><div className="eyebrow">READY WHEN YOU ARE</div><h2 className="display">Bring me the problem.</h2><p>Tell me what you are trying to achieve, what is getting in the way and what the business needs. I&apos;ll come prepared.</p><div className="contact-links"><a href="https://wa.me/917093142389" target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={15}/></a><a href="tel:+917093142389">Call +91 70931 42389 <ArrowUpRight size={15}/></a><a href="mailto:contactsiddb.01@gmail.com">Email me <ArrowUpRight size={15}/></a></div></div><div className="booking-card"><div className="booking-head"><CalendarDays size={20}/><div><strong>Book a conversation</strong><span>30 minutes · short brief first</span></div></div><form className="lead-form" action="https://formsubmit.co/contactsiddb.01@gmail.com" method="POST"><input type="hidden" name="_subject" value="New consulting enquiry from siddharthbhattacharjee.in"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_template" value="table"/><label>Name<input name="name" required placeholder="Your name"/></label><label>Work email<input type="email" name="email" required placeholder="you@company.com"/></label><label>Company / website<input name="company" placeholder="Company or URL"/></label><label>What are you trying to fix?<textarea name="message" rows={4} required placeholder="More leads, conversion, positioning, launch, retention, or something else?"></textarea></label><button className="button" type="submit">Send brief <ArrowUpRight size={16}/></button></form></div></div></section>
</main>}
