import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, CalendarDays, CheckCircle2, Download, Mail } from 'lucide-react';
import Problems from '../components/Problems';
import NewsletterForm from '../components/NewsletterForm';

const quickServices=[
  ['Landing page review','Find the message, proof and conversion friction that may be costing you enquiries.'],
  ['Marketing funnel teardown','A practical look at where prospects drop and what I would fix first.'],
  ['Positioning review','Pressure-test what you say, who you say it to and why customers should care.'],
  ['Founder strategy session','Bring one messy marketing problem. Leave with priorities and a practical next step.'],
];

export default function Home(){return <main>
  <section className="container hero">
    <div className="hero-copy-wrap">
      <div className="eyebrow">Marketing consultant · B2B · B2C</div>
      <h1 className="display">Marketing should help the business <span>grow.</span></h1>
      <p className="hero-copy">I&apos;m Siddharth Bhattacharjee. I&apos;ve spent 11+ years working across B2B and B2C businesses in fintech, technology, commerce, entertainment and consumer products. Today I help businesses make better marketing decisions and turn them into measurable growth.</p>
      <div className="actions"><a className="button" href="#booking">Tell me what&apos;s stuck <ArrowUpRight size={16}/></a><Link className="button alt" href="/services">See how I can help</Link></div>
      <div className="hero-proof"><span>B2B</span><span>B2C</span><span>11+ years</span><span>200M+ customers reached</span></div>
    </div>
    <div className="portrait-wrap"><div className="portrait-frame"><Image src="/siddharth-bhattacharjee.jpg" alt="Siddharth Bhattacharjee, marketing consultant" width={848} height={1264} priority className="portrait"/><div className="portrait-label"><span>SIDDHARTH BHATTACHARJEE</span><span>MARKETING / GROWTH / STRATEGY</span></div></div><div className="floating-stat"><strong>+173%</strong><span>streamer DAU growth in a documented marketing program</span></div></div>
  </section>

  <div className="band"><div className="container ticker"><span>MARKETING STRATEGY</span><span>GROWTH</span><span>B2B</span><span>B2C</span><span>PRODUCT MARKETING</span><span>CRM</span><span>GTM</span><span>SEO</span></div></div>

  <section className="container section" id="problems"><div className="section-head"><h2 className="display">What are you<br/>trying to fix?</h2><p>Start with the problem. Click the one that sounds closest to your situation and I&apos;ll show you how I would think about it.</p></div><Problems/></section>

  <section className="container section" id="services"><div className="section-head"><h2 className="display">Ways to<br/>work together.</h2><p>Sometimes you need a quick outside opinion. Sometimes you need a full marketing strategy. Sometimes you need an experienced marketer in the room for a few months.</p></div><div className="service-levels"><Link href="/services#quick" className="service-level"><span className="num">01 · Focused</span><h3>Fix one important thing.</h3><p>Landing pages, funnels, positioning, GTM reviews and founder strategy sessions.</p><b>See focused services <ArrowUpRight size={15}/></b></Link><Link href="/services#strategy" className="service-level"><span className="num">02 · Projects</span><h3>Build the marketing system.</h3><p>Marketing strategy, growth, B2B, B2C, product marketing, brand and retention projects.</p><b>Explore projects <ArrowUpRight size={15}/></b></Link><Link href="/services#advisory" className="service-level dark-card"><span className="num">03 · Ongoing</span><h3>Bring senior marketing thinking in.</h3><p>Fractional marketing advisory for founders and teams that need direction, prioritisation and hands-on problem solving.</p><b>Explore advisory <ArrowUpRight size={15}/></b></Link></div></section>

  <section className="container section" id="work"><div className="section-head"><h2 className="display">What I&apos;ve<br/>actually done.</h2><p>I don&apos;t want the website to ask you to take my word for it. Here are selected examples from 11+ years across B2B and B2C marketing.</p></div><div className="proof-grid"><div className="proof-big"><div className="num">Entertainment & streaming</div><div className="metric">+173%</div><p>Streamer DAU growth between Aug 2023 and Mar 2024, alongside 89%+ growth in hours from existing streamers and 180%+ improvement in cross-viewership.</p><Link href="/case-studies/streamer-dau-growth">Read the case study <ArrowUpRight size={15}/></Link></div><div className="proof-list"><div><strong>5+ consumer product launches</strong><span>Travel, entertainment, bill payments, insurance and mobility services.</span></div><div><strong>B2B technology</strong><span>Business development and lead generation for web, app and technology services.</span></div><div><strong>Consumer brands & commerce</strong><span>Brand management, marketplace growth and category marketing.</span></div><div><strong>CRM & lifecycle</strong><span>Customer segmentation, messaging, acquisition, retention and engagement.</span></div></div></div></section>

  <section className="dark-section section"><div className="container"><div className="section-head"><h2 className="display">No marketing<br/>theatre.</h2><p>I care about clear thinking, useful work and measurable outcomes. The work can be strategic, creative, analytical or operational depending on what the business needs.</p></div><div className="grid3"><div className="card"><div className="num">01</div><h3>Start with the business</h3><p>What needs to change commercially? That determines what marketing should do.</p></div><div className="card"><div className="num">02</div><h3>Understand the customer</h3><p>Who buys, why they buy, what stops them and what alternatives they already use.</p></div><div className="card"><div className="num">03</div><h3>Make the next move clear</h3><p>A good strategy should tell the team what to do next, what not to do and how to know if it worked.</p></div></div></div></section>

  <section className="container section" id="about"><div className="about-grid"><div><div className="eyebrow">About Siddharth</div><h2 className="display">11+ years across very different marketing problems.</h2></div><div><p className="about-lead">I started in B2B technology sales and lead generation, then moved through fintech, commerce, consumer brands, entertainment and product marketing. That range matters because most business problems do not fit neatly into one marketing discipline.</p><p>Today I use that experience to help founders, business owners and marketing teams make clearer choices about positioning, acquisition, growth, product launches, CRM and where to spend their next marketing rupee.</p><Link className="text-link" href="/services">See how I work <ArrowUpRight size={15}/></Link></div></div></section>

  <section className="container section" id="book"><div className="book-feature"><div className="book-cover"><div className="book-small">SIDDHARTH BHATTACHARJEE</div><div className="book-title">SOVEREIGN<br/>BRAND</div><div className="book-rule"></div><div className="book-sub">Building a brand with a point of view.</div></div><div className="book-copy"><div className="eyebrow">The book</div><h2 className="display">A brand should have<br/>something to say.</h2><p><i>Sovereign Brand</i> is my take on building brands with a clear point of view instead of becoming interchangeable with everyone else in the category.</p><div className="book-actions"><a className="button" href="https://siddster14.gumroad.com/l/sovereignbrand" target="_blank" rel="noreferrer">Buy the book <ArrowUpRight size={16}/></a><Link className="button alt" href="/book">About the book</Link></div><div className="book-note">The book is part of the larger thinking behind my consulting work: understand the customer, make deliberate choices and build something distinctive enough to matter.</div></div></div></section>

  <section className="container section" id="insights"><div className="section-head"><h2 className="display">Useful marketing<br/>thinking.</h2><p>Practical articles on strategy, growth, B2B, B2C, brand, product marketing, CRM, SEO and AI. Built to help you make a better decision.</p></div><div className="blog-grid"><Link className="post featured" href="/blog/how-to-build-a-marketing-strategy"><div className="num">Strategy</div><h3>How to build a marketing strategy that actually drives growth</h3><p>A practical framework for turning a business goal into clear marketing choices.</p><div className="meta">Read the article <ArrowUpRight size={14}/></div></Link><div style={{display:'grid',gap:16}}><Link className="post" href="/blog/b2b-marketing-strategy"><div className="num">B2B</div><h3>B2B marketing strategy: where to start when referrals are doing all the work</h3><div className="meta">Read the article <ArrowUpRight size={14}/></div></Link><Link className="post" href="/blog/landing-page-conversion-checklist"><div className="num">Growth</div><h3>Landing page conversion: the 12 things I check first</h3><div className="meta">Read the article <ArrowUpRight size={14}/></div></Link></div></div><div className="section-link"><Link href="/blog">Browse all insights <ArrowUpRight size={15}/></Link><Link href="/case-studies">Browse case studies <ArrowUpRight size={15}/></Link></div></section>

  <section className="container section resource-strip"><div><div className="eyebrow">Free resources</div><h2 className="display">Useful things you can<br/>take away today.</h2><p>Templates, checklists and frameworks designed to help you work through a marketing problem before you decide whether you need outside help.</p></div><div className="resource-mini-grid"><Link href="/resources/marketing-strategy-canvas"><Download size={18}/><strong>Marketing Strategy Canvas</strong><span>One page to turn business goals into marketing choices.</span></Link><Link href="/resources/landing-page-checklist"><Download size={18}/><strong>Landing Page Checklist</strong><span>12 checks before you spend more money driving traffic.</span></Link><Link href="/resources/gtm-template"><Download size={18}/><strong>GTM Planning Template</strong><span>A simple structure for a new product or service launch.</span></Link><Link href="/resources/brand-positioning-worksheet"><Download size={18}/><strong>Positioning Worksheet</strong><span>Work through audience, alternatives and your reason to believe.</span></Link></div></section>

  <section className="container section newsletter-section"><div className="newsletter-box"><div><div className="eyebrow">The Marketing Brief</div><h2 className="display">One useful marketing idea.<br/>Every week.</h2><p>No generic motivational emails. I&apos;ll share frameworks, examples, case studies and things I&apos;ve learned from working in marketing.</p></div><div><NewsletterForm source="newsletter" tag="Newsletter"/><p className="privacy-note"><Mail size={14}/> You can unsubscribe any time. No spam.</p></div></div></section>

  <section className="container cta" id="contact"><div className="cta-box"><div><div className="eyebrow">Have a marketing problem?</div><h2>Start with the problem.</h2><p className="cta-note">Tell me what you&apos;re building, what is stuck and what outcome matters. I&apos;ll come prepared.</p></div><div><div className="contact-options"><a className="contact-option" href="#booking"><span><strong>Book a conversation</strong><small>Send a short brief first</small></span><CalendarDays size={17}/></a><a className="contact-option" href="https://wa.me/917093142389" target="_blank" rel="noreferrer"><span><strong>WhatsApp</strong><small>Message me directly</small></span><ArrowUpRight size={17}/></a><a className="contact-option" href="tel:+917093142389"><span><strong>Call</strong><small>+91 70931 42389</small></span><ArrowUpRight size={17}/></a><a className="contact-option" href="mailto:contactsiddb.01@gmail.com"><span><strong>Email</strong><small>contactsiddb.01@gmail.com</small></span><ArrowUpRight size={17}/></a></div></div></div></section>

  <section className="container booking" id="booking"><div className="booking-card"><div><div className="eyebrow">Book a conversation</div><h2 className="display">A little context.<br/>Then we talk.</h2><p>Keep it short. This helps me understand whether I&apos;m the right person before we spend time together.</p><div className="booking-points"><span>30-minute call</span><span>Practical next steps</span><span>No sales script</span></div></div><form className="lead-form" action="https://formsubmit.co/contactsiddb.01@gmail.com" method="POST"><input type="hidden" name="_subject" value="New consulting enquiry from siddharthbhattacharjee.in"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_template" value="table"/><input type="hidden" name="_next" value="https://siddharthbhattacharjee.in/#booking"/><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input type="email" name="email" required placeholder="you@company.com"/></label><label>Company / website<input name="company" placeholder="Company or URL"/></label><label>What do you need help with?<select name="service"><option>Marketing strategy</option><option>Landing page / conversion</option><option>B2B marketing</option><option>B2C / ecommerce marketing</option><option>Growth / acquisition</option><option>Brand / positioning</option><option>Product marketing / GTM</option><option>CRM / retention</option><option>Fractional marketing advisory</option><option>Something else</option></select></label><label>Briefly describe the problem<textarea name="message" rows={4} placeholder="What are you trying to achieve? What is getting in the way?"></textarea></label><button className="button" type="submit">Send brief & request a call <ArrowUpRight size={16}/></button><p className="form-note">A calendar link can be connected here once you choose your booking tool. For now, I&apos;ll review the brief and respond directly.</p></form></div></section>
</main>}
