export type BookGuide={slug:string;title:string;description:string;question:string;answer:string;sections:{heading:string;paragraphs:string[]}[]};

export const bookGuides:BookGuide[]=[
 {slug:'ai-marketing-strategy',title:'AI marketing strategy: what should marketers actually redesign?',description:'A practical framework for building an AI marketing strategy around customer decisions, operating models, differentiation and measurement.',question:'What should an AI marketing strategy actually change?',answer:'A useful AI marketing strategy should change the economics and workflow of marketing, not simply add generative AI tools. Start by identifying where marketing work is constrained, then decide which parts should be automated, augmented or deliberately kept human. The strategic questions are customer understanding, differentiation, decision quality, speed of experimentation and measurement.',sections:[
  {heading:'Start with the work, not the tool',paragraphs:['List the recurring marketing work: research, segmentation, copy development, creative variants, reporting, customer support, lifecycle orchestration, sales enablement and experimentation. Identify where time is spent and where quality breaks down.','Then classify each workflow as automate, augment or retain. Automation makes sense when the task is repetitive and rules are stable. Augmentation makes sense when human judgement matters but AI can accelerate the work. Retain the task when the strategic value comes from context, taste, accountability or customer understanding.']},
  {heading:'Do not let AI erase differentiation',paragraphs:['If every competitor can produce ten landing-page variants in an afternoon, more variants are not a durable advantage. The scarce asset moves upstream: distinctive customer insight, positioning, proof, proprietary data, a strong point of view and a better understanding of the decision the customer is making.','That is why AI strategy and brand strategy increasingly overlap. Execution can become cheaper while meaning becomes more valuable.']},
  {heading:'Measure the new system',paragraphs:['Measure cycle time, experimentation velocity, quality, conversion, customer value and cost to serve. A team that generates five times as many assets but creates no additional customer value has automated production, not improved marketing.']}
 ]},
 {slug:'brand-strategy-age-of-ai',title:'Brand strategy in the age of AI: how do you stay differentiated?',description:'How brands can build durable differentiation when AI makes content production, experimentation and execution dramatically easier.',question:'How can a brand stay differentiated when everyone has access to AI?',answer:'A brand stays differentiated by owning a distinctive customer problem, point of view, experience or proof system that competitors cannot reproduce simply by generating similar content. AI lowers the cost of execution. It does not remove the need to make strategic choices about audience, meaning and trust.',sections:[
  {heading:'The production advantage is becoming common',paragraphs:['Text, images, research summaries and creative variations are increasingly accessible. That means production volume is less likely to be a durable competitive advantage. A brand can still use AI to move faster, but speed alone is easier to copy.']},
  {heading:'Own a meaningful choice',paragraphs:['Differentiation starts with a decision about who the brand is especially useful to and what problem it wants to be associated with. The position should create consequences across product, messaging, content, sales and customer experience.','A claim such as innovative or customer-centric does not create a choice. A specific promise, backed by evidence and repeated through the customer experience, can.']},
  {heading:'Build proof into the brand',paragraphs:['In an AI-rich environment, polished claims become cheap. Proof becomes more valuable. Case studies, customer evidence, product behaviour, original research and a consistent operating point of view give customers reasons to believe.']}
 ]},
 {slug:'ai-marketing-operating-model',title:'AI marketing operating model: how should a marketing team use AI?',description:'A practical operating model for deciding where AI belongs in marketing workflows, where humans stay accountable and how to measure the result.',question:'How should a marketing team organise AI work?',answer:'Organise AI around workflows rather than isolated tools. For each recurring process, define the customer outcome, the human owner, the AI role, the quality gate and the metric that determines whether the workflow improved. This prevents AI adoption from becoming a collection of disconnected experiments.',sections:[
  {heading:'Map the workflow',paragraphs:['Take one process such as content production, lifecycle campaign development or market research. Map inputs, decisions, outputs and handoffs. Look for repetitive steps, slow research, inconsistent analysis and manual reporting.']},
  {heading:'Assign AI a specific job',paragraphs:['AI might summarise research, create variants, classify qualitative feedback, generate hypotheses, draft analysis or flag anomalies. The role should be explicit. “Use AI more” is not an operating model.']},
  {heading:'Keep accountability human',paragraphs:['A marketer should remain accountable for positioning, customer interpretation, prioritisation, claims, brand judgement and commercial decisions. AI can accelerate the work without becoming the owner of the decision.']},
  {heading:'Measure the workflow',paragraphs:['Track time saved, quality, iteration speed, error rate and business outcomes. The objective is not AI usage. The objective is a better marketing system.']}
 ]},
 {slug:'brand-differentiation-framework',title:'Brand differentiation framework: a practical way to find a position customers can understand',description:'A practical framework for finding a commercially useful position when competitors use the same category language.',question:'How do you find a differentiated brand position?',answer:'Start with a specific customer situation, identify the alternatives available, find the problem that matters most in that situation, identify the product or organisational truth that gives you an advantage, then build proof around it. Differentiation is not a writing exercise. It is a strategic choice about where the business can be meaningfully better or more relevant.',sections:[
  {heading:'1. Choose the customer situation',paragraphs:['Who is buying, what changed, what are they trying to accomplish and why does the decision matter now? A situation is more useful than a broad demographic segment because it contains urgency and context.']},
  {heading:'2. Map the alternatives',paragraphs:['Customers compare you with competitors, internal solutions, doing nothing and delaying the decision. Understanding those alternatives tells you what your positioning actually has to overcome.']},
  {heading:'3. Find the product truth',paragraphs:['Look for something the business can genuinely defend: a capability, distribution advantage, customer insight, operating model, data asset, experience or way of solving the problem. Do not manufacture differentiation in copy.']},
  {heading:'4. Turn the position into proof',paragraphs:['A position becomes credible when the website, product, sales process, customer stories and content all reinforce it. If the only place the differentiation exists is the homepage headline, it is not yet a competitive position.']}
 ]}
];
