export type Memo={slug:string;title:string;dek:string;theme:string;thesis:string;sections:{heading:string;body:string[]}[]};

export const memos:Memo[]=[
 {slug:'lifecycle-marketing-is-not-broadcasting',title:'Lifecycle marketing is not broadcasting',dek:'The real job of CRM is to improve the next customer decision, not maximise the number of messages sent.',theme:'Lifecycle · CRM',thesis:'A lifecycle programme becomes strategically useful when it knows what the customer has already done, what they are likely to need next and when communication is actually helpful.',sections:[
  {heading:'The common failure',body:['Many CRM teams start with the message calendar. Monday is one campaign, Wednesday is another, Friday is a promotion. The customer is treated as an audience member who needs to be reached.','That reverses the problem. The customer is already moving through a journey. Marketing should decide where communication can improve the journey, not where the calendar has an empty slot.']},
  {heading:'The better model',body:['Start with behaviour: acquisition, first use, repeat use, adjacent use, inactivity and reactivation. Then ask what decision the customer faces at each stage.','This is where next-best-use-case thinking becomes powerful. A recommendation is valuable when it follows a customer signal and reduces uncertainty about what to do next.']},
  {heading:'What to measure',body:['CTR is useful, but it is not the outcome. Measure adoption, repeat behaviour, incremental action and downstream value. A message that generates clicks but no useful behaviour may be a successful notification and an unsuccessful marketing intervention.']}
 ]},
 {slug:'homepage-is-a-growth-surface',title:'A homepage is a growth surface, not a content shelf',dek:'The homepage is one of the most underappreciated decision surfaces in a digital product.',theme:'Growth · Product',thesis:'Every homepage placement makes a bet about what the customer should notice, understand and do next.',sections:[
  {heading:'Why merchandising matters',body:['A content-rich homepage creates a selection problem. Customers do not evaluate every option. They scan, infer and choose. Placement therefore becomes part of product marketing.','The job is not to fill inventory. It is to allocate scarce attention to the content or action most likely to create useful customer behaviour.']},
  {heading:'The metric stack',body:['Start with attention metrics such as CTR, but connect them to streamer or customer outcomes, minutes, conversion, repeat behaviour and cross-use. The further a metric is from the customer outcome, the more dangerous it is to optimise it in isolation.']},
  {heading:'The operating system',body:['A useful merchandising system needs placement rules, audience logic, creative freshness, reporting cadence and a feedback loop. The result is not a better homepage. It is a faster learning system.']}
 ]},
 {slug:'ctr-is-not-the-strategy',title:'CTR is a signal, not the strategy',dek:'Click-through rate can tell you what attracted attention. It cannot tell you whether the business improved.',theme:'Measurement · Growth',thesis:'The mistake is not measuring CTR. The mistake is allowing an attention metric to become the definition of marketing success.',sections:[
  {heading:'Why CTR feels satisfying',body:['It is immediate, comparable and easy to optimise. Change the headline, image or placement and the number moves. That makes it useful for creative diagnostics.','But the customer does not exist to generate clicks. The business needs a downstream action.']},
  {heading:'Build a metric ladder',body:['Use a ladder: exposure, attention, intent, action, repeat action and commercial value. The appropriate level depends on the problem. A brand campaign may sit higher in the ladder. A conversion programme should move much closer to revenue or contribution.']},
  {heading:'The practical rule',body:['Never delete a useful signal. Instead, give it a job. CTR tells you whether the creative or placement earns attention. It should not be asked to prove that the entire intervention created value.']}
 ]},
 {slug:'next-best-action-is-a-marketing-problem',title:'Next-best-action is a marketing problem before it is an ML problem',dek:'Machine learning can rank possibilities. Marketing still has to decide what is useful, acceptable and commercially meaningful.',theme:'AI · Lifecycle · ML',thesis:'The hardest part of next-best-action systems is not prediction. It is translating prediction into a customer experience that improves a decision.',sections:[
  {heading:'Start with the decision',body:['Ask what decision the customer is making and what signal indicates readiness. A model built without that customer logic can become an impressive scoring system with no useful action attached to it.']},
  {heading:'Marketing defines the action space',body:['Marketing needs to define offers, messages, suppression rules, timing, priority and customer experience constraints. ML can help rank the options. It should not be responsible for the entire customer strategy.']},
  {heading:'Incrementality is the test',body:['The right question is not whether recommended customers convert. They may have converted anyway. The right question is whether the recommendation created incremental behaviour compared with a credible control.']}
 ]},
 {slug:'brand-differentiation-after-ai',title:'When AI makes execution cheap, differentiation becomes more valuable',dek:'If every company can generate more content, more variants and more campaigns, the scarce resource moves upstream.',theme:'Brand · AI',thesis:'AI reduces the cost of producing marketing assets. It does not automatically create a reason for a customer to choose one company over another.',sections:[
  {heading:'The new bottleneck',body:['When production becomes cheap, teams can produce more of the same thing. That makes category sameness easier, not harder. The scarce asset becomes a distinctive point of view, customer understanding and proof.']},
  {heading:'What brands should own',body:['Own a problem, an audience, a belief, a distinctive way of solving the problem or a combination that competitors cannot easily reproduce. The goal is not to sound different. It is to be meaningfully different.']},
  {heading:'The implication for marketers',body:['Marketing leaders should spend less time asking what AI can generate and more time deciding what the organisation should believe, prioritise and repeat.']}
 ]},
 {slug:'search-to-decision',title:'The best content does not end at the answer',dek:'Search and AI discovery increasingly reward useful answers. Commercial value comes from what the answer enables the reader to do next.',theme:'SEO · AEO · GEO',thesis:'A high-quality content system should move from question to understanding to evidence to decision, without forcing the reader through a sales pitch.',sections:[
  {heading:'Answer the actual question',body:['Start with the language the buyer uses. Define terms, explain trade-offs, show evidence and make the answer useful even if the reader never contacts you.']},
  {heading:'Then create a path',body:['Once the reader understands the problem, offer the next useful asset: a framework, diagnostic, calculator, example, case study or book. The internal link should follow the reader’s next question.']},
  {heading:'Authority compounds through connection',body:['A strong site is not a pile of articles. It is a connected body of knowledge where experience, analysis, proof and commercial offers reinforce one another.']}
 ]}
];
