export type Post={slug:string;title:string;excerpt:string;date:string;readTime:string;category:string;leadMagnet:string;tag:string;content:{type:'h2'|'h3'|'p'|'ul';text:string}[]};

export const posts:Post[]=[
{slug:'how-to-build-a-marketing-strategy',title:'How to build a marketing strategy that actually drives growth',excerpt:'A practical way to turn a business problem into a focused set of marketing choices, with enough discipline to know what to stop doing.',date:'2026-09-15',readTime:'14 min read',category:'Marketing Strategy',leadMagnet:'Marketing Strategy Canvas',tag:'Marketing Strategy',content:[
{type:'p',text:'Most marketing strategies are not really strategies. They are inventories. There is a section on social media, a section on SEO, a section on paid advertising, a content calendar, some audience personas and a page of KPIs. Everything sounds sensible. The problem is that nothing in the document tells the team what matters more than something else.'},
{type:'p',text:'A useful strategy should make decisions easier. If the company has limited money, limited attention and a finite number of people who can execute, the strategy has to explain where those resources should go and why. It should also make it easier to say no to activities that look attractive but are unlikely to change the business.'},
{type:'h2',text:'Start with the commercial problem, not the marketing channel'},
{type:'p',text:'The first question I would ask a founder or business leader is simple: what needs to be different in the business six or twelve months from now? More qualified opportunities? Better conversion? More repeat purchases? Higher average order value? A new customer segment? A stronger position against a competitor?'},
{type:'p',text:'This matters because the same channel can be right for one problem and completely wrong for another. If a business has plenty of traffic but poor conversion, buying more traffic is not a strategy. If customers buy once and disappear, acquisition may not be the biggest opportunity. If sales depend on the founder personally explaining the value, the problem may be positioning rather than lead generation.'},
{type:'h2',text:'Then identify where the constraint actually sits'},
{type:'p',text:'Think of growth as a chain: attention, demand, consideration, conversion, activation, repeat behaviour and economics. A weak link can make the rest of the system look worse than it really is.'},
{type:'ul',text:'Low awareness means the right people do not know you exist; weak demand means the problem is not being felt strongly enough; poor conversion means the proposition, proof or buying experience is failing; weak activation means customers are not reaching value; poor retention means value is not recurring; weak economics means growth may be buying revenue that is not worth enough.'},
{type:'p',text:'The point is not to create a complicated funnel diagram. It is to find the constraint that is currently limiting growth. That is where strategy should concentrate attention.'},
{type:'h2',text:'Define the customer by situation, not just by demographic'},
{type:'p',text:'A target market such as SMEs, young professionals or healthcare companies is rarely specific enough to guide marketing. Two companies inside the same category can have completely different needs, buying triggers and willingness to pay.'},
{type:'p',text:'I prefer defining a priority customer around a situation. What has happened? What are they trying to accomplish? What makes the problem urgent? What are they using today? Who has to approve the purchase? What happens if they do nothing?'},
{type:'p',text:'That description gives the marketer something useful. It tells you what to say, where to find the audience and what proof will matter.'},
{type:'h2',text:'Positioning is a business decision, not a copywriting exercise'},
{type:'p',text:'Positioning is often treated as a sentence that the agency writes. That is too small a view. The real decision is what you want to be known for, for whom, relative to which alternatives, and why you have the right to own that space.'},
{type:'p',text:'A useful positioning decision creates consequences. You might stop targeting certain customers. You might change the product page. You might change the sales pitch. You might stop using generic claims such as best-in-class and instead prove a narrower advantage.'},
{type:'h2',text:'Choose growth bets instead of building a channel shopping list'},
{type:'p',text:'A good strategy might have three major bets. One could be improving conversion on existing high-intent demand. Another could be building authority in a particular category. A third could be a partner or lifecycle programme. The exact bets depend on the business, but the discipline is the same.'},
{type:'p',text:'For every bet, define the hypothesis, the evidence you expect to see, the leading indicator, the business outcome and the point at which you will change direction. This prevents experimentation from becoming a permanent excuse to keep doing things.'},
{type:'h2',text:'Build measurement around decisions'},
{type:'p',text:'Do not begin with a dashboard. Begin with decisions. What will make you increase investment? What will make you reduce it? What would tell you that the audience is wrong? What would tell you that the proposition is wrong?'},
{type:'p',text:'Traffic, reach, CTR and engagement can be useful diagnostics. They are not automatically business outcomes. The closer a metric is to a customer behaviour that creates value, the more useful it becomes for strategic decisions.'},
{type:'h2',text:'The strategy should make the next ninety days obvious'},
{type:'p',text:'At the end of the process, I want a leadership team to be able to answer five questions without opening a forty-slide deck: who are we prioritising, what problem are we solving, why should customers choose us, what are the few things we are going to do now, and how will we know whether they are working?'},
{type:'p',text:'That is the real test of strategy. Not whether the document looks comprehensive, but whether it improves the quality of the decisions the business makes next.'}]},

{slug:'b2b-marketing-strategy',title:'B2B marketing strategy: where to start when referrals are doing all the work',excerpt:'How B2B businesses can reduce dependence on relationships and build a more repeatable demand system without turning marketing into a lead-volume machine.',date:'2026-09-15',readTime:'13 min read',category:'B2B Marketing',leadMagnet:'B2B Marketing Canvas',tag:'B2B',content:[
{type:'p',text:'Referrals are one of the best acquisition sources a B2B company can have. They arrive with trust attached, the buyer often already understands the category and the sales conversation starts much further down the funnel.'},
{type:'p',text:'The problem is not referrals. The problem is when referrals are the only thing keeping the pipeline alive. The business then becomes dependent on relationships that may be uneven, difficult to forecast and difficult to scale.'},
{type:'h2',text:'First, understand what referrals are doing for you'},
{type:'p',text:'Before building a demand programme, look at your existing referrals. Which customers refer? What problem were they buying you to solve? At what point in their buying journey did someone recommend you? What did the referring person actually say about your business?'},
{type:'p',text:'This exercise often reveals the real positioning. A company may describe itself as a full-service marketing partner while customers consistently refer it for one particular problem. That pattern is valuable evidence. Marketing should not ignore it because the website says something broader.'},
{type:'h2',text:'Define the best-fit account around a buying situation'},
{type:'p',text:'Industry is usually a poor proxy for need. A technology company can be a great customer or a terrible one depending on stage, commercial model, growth target and internal capability.'},
{type:'p',text:'Build the ideal customer definition around a trigger. Perhaps the company has raised funding and needs a repeatable acquisition engine. Perhaps sales has plateaued because the category has become crowded. Perhaps a founder-led sales process is no longer enough. A trigger creates urgency, and urgency makes marketing much more relevant.'},
{type:'h2',text:'Translate your proposition into business language'},
{type:'p',text:'B2B buyers do not wake up wanting a marketing campaign, a CRM workflow or an SEO programme. They want the business result those things are supposed to create.'},
{type:'p',text:'If the product reduces operational cost, say how. If it helps a sales team win more of the right opportunities, explain the mechanism. If the value is risk reduction, make the risk concrete. The job of marketing is to connect the capability to the business problem in language the buying group can use internally.'},
{type:'h2',text:'Create demand before you ask for the meeting'},
{type:'p',text:'A company that relies on referrals can fall into a trap: every piece of content becomes a disguised sales pitch. That makes the content less useful to buyers who are still trying to understand the problem.'},
{type:'p',text:'Better B2B content helps a buyer make a decision. It can explain why a problem occurs, show how to diagnose it, compare approaches, expose a common mistake, provide a framework or demonstrate what good looks like. The commercial value comes from being useful before the buyer is ready to buy.'},
{type:'h2',text:'Build the sales and marketing loop'},
{type:'p',text:'Marketing should not hand sales a spreadsheet of leads and disappear. Sales should be telling marketing which problems are creating urgency, which objections are recurring, which messages get meetings and which opportunities become revenue.'},
{type:'ul',text:'Define what a qualified opportunity means; record the trigger that created the opportunity; capture objections and lost reasons; connect content and campaigns to pipeline where possible; review quality by segment rather than celebrating total lead volume.'},
{type:'h2',text:'Do not try to replace referrals overnight'},
{type:'p',text:'A sensible transition is to keep referrals strong while building one additional source of demand. If your strongest opportunity is category education, build a serious insight programme. If buyers search when a trigger occurs, build useful search content and landing pages. If the market is relationship-heavy, build a deliberate partner strategy.'},
{type:'p',text:'The objective is not to make referrals less important. It is to make the business less fragile when referrals slow down.'},
{type:'h2',text:'What a good starting system looks like'},
{type:'p',text:'Start with one clearly defined customer situation, one sharp proposition, a small set of high-value problems to educate the market about, a conversion path that does not demand a sales call immediately, and a sales feedback loop that tells marketing what is actually turning into revenue.'},
{type:'p',text:'That is enough to start. The sophistication can come later. The important shift is from hoping the right person gets introduced to you toward becoming useful to the right person before the introduction happens.'}]},

{slug:'landing-page-conversion-checklist',title:'Landing page conversion: the 12 things I check first',excerpt:'Before spending more on traffic, diagnose whether the page is making it easy for the right visitor to understand, trust and act.',date:'2026-09-15',readTime:'12 min read',category:'Growth',leadMagnet:'Landing Page Checklist',tag:'Growth',content:[
{type:'p',text:'When a landing page underperforms, the instinct is often to redesign it. New hero image, new colours, new buttons, perhaps a shorter form. Sometimes that helps. More often, the page has a decision problem rather than a design problem.'},
{type:'p',text:'I start by asking what the visitor needs to believe before taking the next step. Then I work backwards through the page.'},
{type:'h2',text:'1. Is the promise clear before the scroll?'},
{type:'p',text:'The first screen should answer three things quickly: what is this, who is it for, and why should I care? Clever headlines often fail because they optimise for personality instead of comprehension.'},
{type:'h2',text:'2. Does the page continue the promise that brought the visitor here?'},
{type:'p',text:'A visitor arriving from a specific campaign has a mental expectation. If the ad says one thing and the landing page opens with something broader, trust is lost before the visitor has even evaluated the offer.'},
{type:'h2',text:'3. Is the audience obvious?'},
{type:'p',text:'Specificity helps the right person recognise themselves. It can also make the wrong visitor leave, which is not necessarily a bad outcome. A business should optimise for valuable conversions, not maximum form completion.'},
{type:'h2',text:'4. Is the offer concrete?'},
{type:'p',text:'A visitor should know what they get and what happens next. Free consultation is vague. A 30-minute growth diagnosis focused on acquisition, conversion and retention is more tangible because the work has shape.'},
{type:'h2',text:'5. Is there proof at the point where doubt appears?'},
{type:'p',text:'Proof should not be treated as decoration. Ask what claim the reader might doubt, then place evidence close to that claim. Specific outcomes are stronger than a wall of logos. A short explanation of how the result was achieved is stronger than an unexplained percentage.'},
{type:'h2',text:'6. Does the page answer the obvious objection?'},
{type:'p',text:'Price, fit, implementation effort, switching cost, credibility and internal approval are common sources of hesitation. Good pages do not wait for the buyer to invent these questions.'},
{type:'h2',text:'7. Is the call to action asking for the right commitment?'},
{type:'p',text:'The CTA should match buying intent. Someone discovering a problem may want a framework or diagnostic. Someone comparing suppliers may be ready for a conversation. Asking everyone for a demo is lazy funnel design.'},
{type:'h2',text:'8. Is the form creating unnecessary friction?'},
{type:'p',text:'Every field has a cost. Ask for information that changes what happens next. If the team never uses a field, remove it. If qualification matters, explain why the information is useful.'},
{type:'h2',text:'9. Does the page make the next step feel safe?'},
{type:'p',text:'The visitor is taking a risk. They may receive unwanted calls, be pushed into a sales process or waste time. Explain what happens after submission. Reducing uncertainty can be more powerful than changing button colour.'},
{type:'h2',text:'10. What happens after conversion?'},
{type:'p',text:'A conversion is not the end of the funnel. Check confirmation, response time, qualification, scheduling, follow-up and whether the lead actually reaches the right person.'},
{type:'h2',text:'11. Are you judging conversion rate without looking at lead quality?'},
{type:'p',text:'A page that converts ten percent of visitors is not automatically better than one that converts three percent. If the ten percent rarely become customers and the three percent contain your best buyers, the second page may be doing the better commercial job.'},
{type:'h2',text:'12. Are you testing a hypothesis or just changing things?'},
{type:'p',text:'A useful test starts with a belief about the customer. For example, if you believe visitors are unsure whether the service is relevant to their company size, change the message to address that uncertainty. Then define what evidence would support or weaken the hypothesis.'},
{type:'p',text:'The best landing page optimisation is usually not a hunt for a magic conversion rate. It is a disciplined process of removing uncertainty for the right customer and making the next step feel like the natural continuation of the decision.'}]},

{slug:'brand-positioning-framework',title:'A practical brand positioning framework for businesses that sound like everyone else',excerpt:'How to find a clearer reason for customers to choose you without hiding behind a complicated brand manifesto.',date:'2026-09-15',readTime:'13 min read',category:'Brand',leadMagnet:'Brand Positioning Worksheet',tag:'Brand',content:[
{type:'p',text:'There is a particular kind of website that makes me nervous. It has polished photography, a confident headline and a list of adjectives: innovative, trusted, customer-centric, world-class, seamless. Nothing is obviously wrong. The problem is that the same words appear on the competitor websites.'},
{type:'p',text:'When that happens, the answer is not usually better copy. The business needs a sharper position.'},
{type:'h2',text:'Positioning starts with a choice'},
{type:'p',text:'A position is not a description of everything the company can do. It is a decision about what the company should mean to a particular customer in a particular buying situation.'},
{type:'p',text:'That means you have to be willing to leave some space unclaimed. If the business tries to be premium and affordable, specialist and full-service, innovative and dependable, it may end up being memorable for none of those things.'},
{type:'h2',text:'Define the customer more narrowly than the market'},
{type:'p',text:'A category such as fintech, healthcare, SaaS or professional services is too broad to be a positioning target. Find the customer situation where your advantage matters most.'},
{type:'p',text:'What are they trying to achieve? What has changed? What alternatives are they considering? What makes the decision difficult? The answers reveal the context in which your position has to work.'},
{type:'h2',text:'Your competition includes doing nothing'},
{type:'p',text:'One of the most useful positioning exercises is to list every alternative a customer might choose. A competitor is obvious. An internal team, an existing supplier, a spreadsheet, a manual process, a cheaper workaround or simply postponing the decision can be equally important.'},
{type:'p',text:'This changes the marketing conversation. You are no longer trying to explain why you are better than a named competitor. You are explaining why changing the current situation is worth it.'},
{type:'h2',text:'Find the difference that actually matters'},
{type:'p',text:'A difference only matters if it changes a customer decision. Faster matters when speed has a commercial consequence. Specialist matters when generalists cannot solve the problem. Better support matters when failure is expensive.'},
{type:'p',text:'Then comes the second test: can you prove the difference? A claim that matters but cannot be demonstrated is fragile. The strongest positions sit where customer importance and business credibility overlap.'},
{type:'h2',text:'Turn positioning into evidence'},
{type:'p',text:'If you want to own a position, your website, sales process, product experience and customer stories should reinforce it. A company claiming to be the specialist in a problem should demonstrate depth, not just say specialist.'},
{type:'ul',text:'Show the specific problems you solve; explain your approach; publish useful thinking; make case studies about decisions and outcomes; demonstrate relevant expertise; use customer language that reinforces the position.'},
{type:'h2',text:'A position should make some decisions easier'},
{type:'p',text:'Once the position is clear, it should influence what the company does. Which customers should sales prioritise? Which products deserve investment? Which partnerships make sense? Which content should be created? Which requests should be declined?'},
{type:'p',text:'If the positioning document sits in a brand folder and never changes a decision, it has not done its job.'},
{type:'h2',text:'The simplest test'},
{type:'p',text:'Ask a customer who knows you well: when someone in your market has the problem we solve, what would you say we are particularly good at? Compare that answer with the sentence on the website.'},
{type:'p',text:'If the customer answer is more specific and more interesting, you may already have a strong position. The work is to recognise it, prove it and make the rest of the business consistent with it.'}]},

{slug:'go-to-market-strategy',title:'Go-to-market strategy: a simple framework for launching something new',excerpt:'A GTM plan should explain who the product is for, why the problem matters now, how the buyer will discover it and what has to happen after launch.',date:'2026-09-15',readTime:'14 min read',category:'Product Marketing',leadMagnet:'GTM Planning Template',tag:'Product Marketing',content:[
{type:'p',text:'A launch calendar can be full and still have no go-to-market strategy. There may be a teaser campaign, a webinar, social posts, sales enablement, a press release and a launch event. Everyone is busy. Nobody has answered the most important question: why should this particular customer change what they are doing?'},
{type:'p',text:'A GTM plan connects product value to a specific market situation. It explains who has the problem, why the problem is important, what makes the product a credible solution, how buyers will encounter it and what needs to happen for the first use to become a habit.'},
{type:'h2',text:'Choose the launch objective before choosing the channels'},
{type:'p',text:'A launch can have several ambitions, but one usually matters most. Are you validating demand? Entering a new segment? Replacing an existing product? Driving adoption of something customers already have access to? The answer changes the plan.'},
{type:'h2',text:'Define the audience by trigger'},
{type:'p',text:'The best launch audience is often defined by a moment. A new regulation, a funding round, a change in team size, a new technology, a cost problem or a new customer expectation can create the need.'},
{type:'p',text:'The trigger is useful because it gives marketing a context. Instead of telling everyone about a new feature, you can explain why a person experiencing a particular change should pay attention.'},
{type:'h2',text:'Write the message before producing the assets'},
{type:'p',text:'The message should answer four questions: what problem is changing, what is the new way of solving it, what outcome should the customer expect, and why should they believe you?'},
{type:'p',text:'If the team cannot answer those questions in plain language, producing more creative will not fix the launch. It will simply distribute an unclear story more widely.'},
{type:'h2',text:'Design the journey, not the announcement'},
{type:'p',text:'A buyer may need to encounter the product several times. They might first see a useful explanation, then a comparison, then a customer example, then a product demonstration and finally a commercial offer.'},
{type:'p',text:'That sequence is particularly important for products that require behaviour change. The launch should reduce uncertainty at each stage rather than expecting one announcement to create adoption.'},
{type:'h2',text:'Plan for sales objections before launch'},
{type:'p',text:'Sales teams are often the first place where the GTM strategy breaks. Marketing says the product is simple, while buyers ask about implementation, switching, integrations, security, pricing or internal ownership.'},
{type:'p',text:'Build those questions into the launch. Good enablement is not a collection of pretty slides. It is a set of useful answers to the questions that stop a buyer from moving.'},
{type:'h2',text:'Measure adoption, not just attention'},
{type:'p',text:'Launch metrics such as reach, traffic and registrations can tell you whether the message travelled. They do not tell you whether the product created value.'},
{type:'ul',text:'Measure activation; time to first value; repeat use; conversion from trial to paid; expansion where relevant; retention; objections; sales cycle; and revenue quality.'},
{type:'h2',text:'The post-launch period is part of GTM'},
{type:'p',text:'A launch is often treated as finished after the announcement. In reality, that is when the market begins giving you evidence. Which audience responded? Which message created interest? Where did customers get stuck? What did sales hear? Which use case appeared unexpectedly?'},
{type:'p',text:'The best GTM teams use those signals to tighten positioning and improve the product experience. The launch becomes the beginning of a learning system, not the end of a campaign.'}]},

{slug:'crm-retention-strategy',title:'CRM and retention strategy: stop treating customers like a broadcast list',excerpt:'A practical lifecycle approach to deciding what customers need next, and why relevance matters more than message volume.',date:'2026-09-15',readTime:'12 min read',category:'CRM & Retention',leadMagnet:'Lifecycle Marketing Map',tag:'CRM',content:[
{type:'p',text:'Many CRM programmes are built around the question, what message can we send this week? That question is already too late. The better question is, what does this customer need to do next if we want them to get more value from the relationship?'},
{type:'p',text:'Once you ask it that way, CRM becomes less about broadcasting and more about customer behaviour.'},
{type:'h2',text:'Start by mapping states, not campaigns'},
{type:'p',text:'A customer who has just signed up is not the same as a customer who has used the product three times, and neither is the same as someone who has stopped buying. They have different problems.'},
{type:'ul',text:'New prospect; newly acquired customer; activated customer; repeat customer; high-value customer; at-risk customer; lapsed customer.'},
{type:'p',text:'The exact states will vary, but the principle is useful: define the behaviours that distinguish one state from another.'},
{type:'h2',text:'Find the moment of first value'},
{type:'p',text:'Retention problems often begin much earlier than churn. If a customer never reaches the point where they experience the promised value, later reminders will not rescue the relationship.'},
{type:'p',text:'Identify the behaviour that correlates with a customer understanding the value. Then make that behaviour easier. Onboarding, education, product prompts, service follow-up and CRM should work together here.'},
{type:'h2',text:'Segment by behaviour before demographics'},
{type:'p',text:'Demographic segmentation can be useful, but behaviour often tells you more about what to do next. Recency, frequency, purchase history, usage, category preference and intent can create actionable groups.'},
{type:'p',text:'The test is simple: if a segment exists, can you describe what you would do differently for that group? If not, the segment may not be useful.'},
{type:'h2',text:'Give every message one job'},
{type:'p',text:'A good lifecycle message helps the customer make a useful next move. Complete setup. Use a feature. Reorder. Renew. Discover a relevant product. Solve a problem. Invite a colleague. Ask for help.'},
{type:'p',text:'Messages become noise when the business has no clear reason for sending them. The customer experiences the volume, while the company sees only campaign activity.'},
{type:'h2',text:'Retention is partly a product problem'},
{type:'p',text:'Marketing cannot compensate indefinitely for a weak value proposition or poor product experience. If customers leave because the product does not deliver what they expected, more email is not the solution.'},
{type:'p',text:'The CRM team should therefore bring retention evidence back into the wider business. Which customers stay? Which customers leave? What did they expect? What did they actually experience?'},
{type:'h2',text:'Measure behaviour, not message activity'},
{type:'p',text:'Open rates and clicks can help diagnose creative or delivery issues, but the commercial question is whether the customer did something valuable.'},
{type:'ul',text:'Activation; repeat purchase; retention; renewal; expansion; reduced time to value; reduced churn; customer value.'},
{type:'h2',text:'The goal is fewer messages, better moments'},
{type:'p',text:'A mature CRM programme often sends fewer messages because it has a better understanding of when communication is useful. The ambition is not to occupy more of the customer’s inbox. It is to become useful at moments that matter.'}]},

{slug:'seo-in-the-age-of-ai-search',title:'SEO in the age of AI search: what marketers should optimise for now',excerpt:'Search is changing from a list of links into answers and recommendations. The response is not to publish more generic content.',date:'2026-09-15',readTime:'13 min read',category:'SEO',leadMagnet:'Marketing Strategy Canvas',tag:'SEO',content:[
{type:'p',text:'There is a temptation to describe AI search as the death of SEO. I do not think that is the useful way to look at it. The more important change is that information is being selected, summarised and recommended in new ways.'},
{type:'p',text:'That makes the underlying question more important: why should a search system or a human consider your company a credible source on this problem?'},
{type:'h2',text:'Stop thinking of content as a collection of keywords'},
{type:'p',text:'A page can target a keyword and still be a poor answer. It may define the term without helping the reader make a decision. It may repeat information that appears everywhere else. It may never explain what the concept means in the context of the buyer’s problem.'},
{type:'p',text:'Useful search content starts with the decision the reader is trying to make. What are they comparing? What could go wrong? What should they measure? What is the difference between two approaches? When should they not buy anything at all?'},
{type:'h2',text:'Build authority around a problem you actually understand'},
{type:'p',text:'Topical authority is not simply publishing a large number of pages. It is building a connected body of useful knowledge around a subject where you have legitimate expertise.'},
{type:'p',text:'For a consulting business, that can mean a strong combination of frameworks, detailed articles, case studies, service pages and practical resources. The commercial pages show what you do. The insight pages show how you think. The cases show what happens when the thinking is applied.'},
{type:'h2',text:'First-hand experience is becoming more valuable'},
{type:'p',text:'Generic summaries are easy to produce. What is harder to reproduce is an observation earned from doing the work: the pattern you keep seeing, the decision clients struggle with, the reason a common approach fails, or the trade-off that is usually hidden.'},
{type:'p',text:'That is where a consultant has an advantage. Do not hide the useful thinking behind vague claims about expertise. Show the thinking.'},
{type:'h2',text:'Answer the next question on the same page'},
{type:'p',text:'A strong article anticipates what the reader will ask next. If you explain customer acquisition cost, explain why CAC can rise, how to segment it and what to do before cutting spend. If you discuss positioning, explain how to test whether the position is credible.'},
{type:'p',text:'This creates a better experience for humans and a stronger information structure for systems trying to understand the topic.'},
{type:'h2',text:'Connect insight to evidence'},
{type:'p',text:'If you make a claim, show how you know. Use first-hand examples where you can. Cite credible external evidence when the point depends on research. Be clear when something is a hypothesis rather than a proven result.'},
{type:'h2',text:'Make the site a connected knowledge system'},
{type:'p',text:'A reader should be able to move from an article to a related framework, from the framework to a case study, and from the case study to the relevant consulting service. That is more useful than a website where every page is isolated.'},
{type:'h2',text:'The real SEO advantage is trust'},
{type:'p',text:'Search tactics change. The durable asset is a body of work that makes a buyer think, this person understands the problem I am dealing with. That is also the kind of content that has a chance of being referenced when search becomes more conversational.'},
{type:'p',text:'For a consulting business, that is the standard worth aiming for. Not more pages. Better evidence of expertise.'}]},

{slug:'marketing-consultant-vs-marketing-agency',title:'Marketing consultant vs marketing agency: which one does your business need?',excerpt:'A practical way to decide whether the problem is strategy, execution capacity, specialist capability or senior judgement.',date:'2026-09-15',readTime:'11 min read',category:'Consulting',leadMagnet:'Marketing Strategy Canvas',tag:'Consulting',content:[
{type:'p',text:'Businesses often compare consultants and agencies as if one is simply a cheaper or more expensive version of the other. That misses the real difference. The useful question is not who costs less. It is what problem you are actually trying to solve.'},
{type:'h2',text:'If the problem is deciding what to do, start with strategy'},
{type:'p',text:'A consultant is useful when the business has too many possible actions and not enough confidence about which ones deserve investment. This might involve positioning, growth strategy, GTM, marketing effectiveness, customer acquisition, retention or a broader commercial problem.'},
{type:'p',text:'The output should be clarity. What is the problem? What is causing it? What are the choices? What should happen first? What should not happen? What evidence would change the recommendation?'},
{type:'h2',text:'If the strategy is clear and capacity is missing, an agency may be right'},
{type:'p',text:'An agency can be the better answer when the business knows what it wants executed and needs specialist capacity. Creative production, paid media, SEO execution, development, video, design or campaign operations can all benefit from a dedicated team.'},
{type:'p',text:'The danger is hiring execution to compensate for strategic uncertainty. If the proposition is unclear, an agency can produce a large amount of polished activity around the wrong problem.'},
{type:'h2',text:'Sometimes the answer is both'},
{type:'p',text:'A consultant can establish the strategy, positioning, priorities and measurement system while an agency executes specific parts of the plan. This can work well when responsibilities are explicit.'},
{type:'ul',text:'Consultant owns the problem definition, strategic choices and senior decision support; agency owns agreed execution; internal team owns commercial context, approvals and customer knowledge; everyone shares the business outcome.'},
{type:'h2',text:'Ask what you need to know in ninety days'},
{type:'p',text:'A useful way to decide is to ask what uncertainty is holding the business back. If you do not know which customer to prioritise, what proposition will win or which growth lever is worth funding, you have a strategy problem. If you know those things but cannot produce the work fast enough, you have a capacity problem.'},
{type:'h2',text:'Do not buy a service catalogue'},
{type:'p',text:'The strongest partner is the one whose capability matches the bottleneck. If your bottleneck is senior judgement, buying twenty deliverables is unlikely to solve it. If the bottleneck is production capacity, paying for strategy without execution support will not create output.'},
{type:'h2',text:'The commercial test'},
{type:'p',text:'Before hiring anyone, write down the business outcome you need, the decision you are currently unable to make, the capability you are missing and what success should look like. Then compare providers against that problem rather than comparing generic lists of services.'}]},

{slug:'full-stack-marketing',title:'Full-stack marketing: why modern marketers need to think beyond channels',excerpt:'The strongest marketers connect brand, growth, product, CRM, data and distribution into one customer system.',date:'2026-09-15',readTime:'12 min read',category:'Marketing Strategy',leadMagnet:'Marketing Strategy Canvas',tag:'Marketing Strategy',content:[
{type:'p',text:'Customers do not experience your organisation as separate marketing functions. They do not see the paid media team, CRM team, brand team and product marketing team as separate systems. They experience one promise, one product and one journey.'},
{type:'p',text:'That is why channel expertise alone is not enough for senior marketing work. Someone has to understand how the pieces interact.'},
{type:'h2',text:'The channel can look healthy while the business gets weaker'},
{type:'p',text:'A campaign can have excellent click-through rates and still be a poor business decision if it attracts customers who never activate or retain. A content programme can generate traffic and still create little demand. A CRM programme can lift engagement while annoying customers with unnecessary messages.'},
{type:'p',text:'The senior marketing question is what changed in the customer system because we did this?'},
{type:'h2',text:'Brand creates preference'},
{type:'p',text:'Brand is not a decorative layer added before performance marketing. It influences whether a customer notices you, remembers you, trusts you and gives you consideration when alternatives exist.'},
{type:'h2',text:'Acquisition creates the opportunity'},
{type:'p',text:'Acquisition brings potential customers into the system. The important question is not only how much demand was created, but what kind of demand it was and whether the rest of the business can convert it profitably.'},
{type:'h2',text:'Product marketing connects promise to behaviour'},
{type:'p',text:'Product marketing is where the customer problem, proposition, positioning, launch and product experience meet. It should reduce the gap between what the company says and what the customer needs to understand to adopt the product.'},
{type:'h2',text:'CRM creates repeat value'},
{type:'p',text:'Once the customer is acquired, the marketing job changes. The business needs to help the customer reach value, repeat useful behaviour and stay long enough for the economics to work.'},
{type:'h2',text:'Analytics closes the loop'},
{type:'p',text:'Analytics should not be a reporting department that produces numbers after decisions have been made. It should help the team understand where the system is working, where it is leaking and which hypotheses deserve another test.'},
{type:'h2',text:'The five questions a full-stack marketer keeps asking'},
{type:'ul',text:'Who are we trying to change? What do they currently believe or do? What should they believe or do instead? What intervention can move that behaviour? How will we know the change was valuable to the business?'},
{type:'p',text:'Those questions connect brand, acquisition, product, CRM and measurement without pretending they are the same discipline.'},
{type:'h2',text:'This is why senior marketing should look more like business leadership'},
{type:'p',text:'The more senior the role, the less useful it becomes to say my team owns this channel. Senior marketers have to work across functions because customers do. The job is to make the whole system more coherent, not simply to make one part of it more efficient.'}]},

{slug:'how-to-reduce-customer-acquisition-cost',title:'How to reduce customer acquisition cost without simply cutting ad spend',excerpt:'CAC is usually a symptom of the wider growth system. Here are the levers I would examine before reaching for the budget knife.',date:'2026-09-15',readTime:'13 min read',category:'Growth',leadMagnet:'Marketing Strategy Canvas',tag:'Growth',content:[
{type:'p',text:'When customer acquisition cost rises, the easiest action is to reduce spend. It feels disciplined because the number comes down immediately. The problem is that you may have reduced acquisition rather than improved acquisition.'},
{type:'p',text:'The better question is why the business is paying more to acquire a customer and whether the extra cost is actually bad.'},
{type:'h2',text:'Start by segmenting CAC'},
{type:'p',text:'A blended CAC can hide almost everything that matters. Look at acquisition cost by customer type, product, geography, channel, campaign and customer quality where the data allows it.'},
{type:'p',text:'You may discover that one segment is expensive but valuable, while another looks efficient but produces poor retention. Cutting the expensive segment because its first-order CAC is high could destroy value.'},
{type:'h2',text:'Check whether the traffic is wrong'},
{type:'p',text:'Before optimising conversion, ask whether the people arriving are the people you want. If targeting has become broad, the landing page may be blamed for a demand-quality problem.'},
{type:'h2',text:'Improve conversion before buying more traffic'},
{type:'p',text:'If the right visitors are failing to act, more traffic scales the leak. Review message match, offer, proof, objections, page friction, response time and the quality of the follow-up.'},
{type:'h2',text:'Improve activation'},
{type:'p',text:'A customer who never reaches value is expensive even if the acquisition cost looks acceptable. Faster onboarding, clearer product education, better first use and better sales handoff can increase the economic value of the same acquisition spend.'},
{type:'h2',text:'Increase customer value'},
{type:'p',text:'Retention and repeat behaviour change the economics of acquisition. A business that can keep a customer longer can often afford to pay more to acquire the right customer.'},
{type:'ul',text:'Retention; repeat purchase; expansion; cross-sell; higher average order value; improved activation; reduced service cost.'},
{type:'h2',text:'Build more than one acquisition engine'},
{type:'p',text:'Paid media is useful, but dependency is risky. Search, content, referrals, partnerships, product-led distribution, communities and lifecycle programmes can each play different roles.'},
{type:'p',text:'The goal is not to make every channel profitable immediately. It is to create a portfolio where one channel does not carry the entire acquisition burden.'},
{type:'h2',text:'Know when CAC is supposed to rise'},
{type:'p',text:'A company entering a new segment or pursuing a larger customer may deliberately accept a higher acquisition cost. The relevant question is whether the resulting customer economics justify it.'},
{type:'p',text:'Good growth management is therefore not about achieving the lowest possible CAC. It is about acquiring customers whose value, retention and strategic importance make the investment sensible.'}]},

{slug:'marketing-for-small-businesses',title:'Marketing for small businesses: what to do when you cannot afford to do everything',excerpt:'A practical prioritisation framework for business owners who need marketing to create results without building a large team.',date:'2026-09-15',readTime:'13 min read',category:'Small Business',leadMagnet:'Marketing Strategy Canvas',tag:'Small Business',content:[
{type:'p',text:'Small businesses often receive marketing advice designed for companies with specialists, budgets and time that do not exist. Build a content team. Run paid search. Post every day. Launch an email newsletter. Do SEO. Make videos. Start a podcast.'},
{type:'p',text:'The problem is not that these activities are inherently bad. It is that doing all of them badly can be worse than doing two things well.'},
{type:'h2',text:'Choose the customer where you have an unfair advantage'},
{type:'p',text:'Start with the customer who gets the clearest value from what you do. A narrower target can make every other marketing decision easier: the message becomes clearer, referrals become easier to describe and content becomes more specific.'},
{type:'h2',text:'Fix the conversion path before adding channels'},
{type:'p',text:'If someone is already interested, can they understand the offer, trust the business and take the next step without unnecessary friction? Check the website, enquiry process, response time, pricing explanation, proof and follow-up.'},
{type:'p',text:'A small improvement here can be worth more than another channel because it affects the demand you already have.'},
{type:'h2',text:'Build one useful content engine'},
{type:'p',text:'Do not create separate ideas for LinkedIn, Instagram, email and the website. Start with real customer questions. Answer one properly, then adapt that thinking into the formats your customers actually use.'},
{type:'p',text:'This also creates a compounding asset. The answer can help a prospect today, become sales material tomorrow and remain useful on the website months later.'},
{type:'h2',text:'Use proof as a growth asset'},
{type:'p',text:'Small businesses often have good results but weak documentation. Turn successful work into short case stories. What was the situation? What was difficult? What did you change? What happened? What did the customer learn?'},
{type:'h2',text:'Choose a channel because of customer behaviour'},
{type:'p',text:'Do not choose a channel because somebody says it is working in your industry. Choose it because your priority customer is there, has a relevant problem there or uses that channel to research the decision.'},
{type:'h2',text:'Create a simple weekly operating rhythm'},
{type:'ul',text:'One customer insight; one useful piece of content; one improvement to the conversion path; one follow-up with an existing customer or prospect; one review of the numbers that matter.'},
{type:'p',text:'That may sound small. That is the point. A system that can be sustained for a year is more valuable than a burst of activity that disappears after three weeks.'},
{type:'h2',text:'Measure the business, not the marketing theatre'},
{type:'p',text:'Track enquiries, qualified opportunities, sales, repeat customers and customer value. Use reach, clicks and engagement as supporting evidence, not as the definition of success.'},
{type:'p',text:'Small business marketing works best when it is treated as a sequence of commercial decisions rather than an endless list of content tasks.'}]},

{slug:'how-to-choose-a-marketing-consultant',title:'How to choose a marketing consultant without buying another strategy deck',excerpt:'What to look for when you need senior marketing judgement, and how to tell whether a consultant will actually help the business move.',date:'2026-09-15',readTime:'12 min read',category:'Consulting',leadMagnet:'Marketing Strategy Canvas',tag:'Consulting',content:[
{type:'p',text:'Hiring a marketing consultant can go wrong in a very specific way: the business pays for clarity and receives a document. The document is polished, the recommendations are sensible, and six weeks later nothing important has changed.'},
{type:'p',text:'The problem is not that strategy is unnecessary. The problem is that strategy has been separated from decisions and implementation.'},
{type:'h2',text:'Start by defining the decision you need help with'},
{type:'p',text:'Do not begin with a list of services. Write down the uncertainty. Are you unsure which customer to prioritise? Whether the proposition is strong enough? Why acquisition is getting expensive? Whether the team is working on the right things? Whether you need an agency or internal capability?'},
{type:'p',text:'The better the problem definition, the easier it is to judge a consultant.'},
{type:'h2',text:'Look for relevant problem experience, not just logos'},
{type:'p',text:'A large client list can be impressive and still tell you little about whether someone understands your problem. Ask for examples of situations similar to yours and, more importantly, ask what they actually did.'},
{type:'h2',text:'Listen to how they diagnose the problem'},
{type:'p',text:'A good consultant should ask uncomfortable questions. What is the commercial objective? What have you already tried? What evidence says this is the problem? What would make the recommendation wrong? Where does the team disagree?'},
{type:'p',text:'If the consultant jumps straight to tactics, you may be buying activity before diagnosis.'},
{type:'h2',text:'Ask what will change after the engagement'},
{type:'p',text:'The answer should be specific. A clearer position. A prioritised growth plan. A better acquisition model. A new GTM approach. A measurement system. A team that knows what to do next.'},
{type:'p',text:'If the answer is simply a strategy document, ask how the document will change behaviour.'},
{type:'h2',text:'Understand the working model'},
{type:'p',text:'Consulting is collaborative. The consultant needs access to people, customers, data and decisions. The business needs to provide context and make choices. Be wary of both extremes: the consultant who wants to do everything alone and the consultant who expects the client to do all the thinking.'},
{type:'h2',text:'Ask how disagreement is handled'},
{type:'p',text:'You are not hiring a consultant to agree with everything you already believe. You are paying for judgement. Ask how they respond when the evidence points somewhere the leadership team does not want to go.'},
{type:'h2',text:'A simple selection scorecard'},
{type:'ul',text:'Problem fit; quality of diagnosis; evidence of relevant work; commercial understanding; clarity of working model; ability to work with your team; quality of thinking; willingness to say what should not be done.'},
{type:'p',text:'The best consultant is not the person who produces the most impressive presentation. It is the person who helps the business see the problem more clearly, make better choices and move with greater confidence.'}]},

{slug:'marketing-forecasting-and-revenue',title:'Marketing forecasts: how to build one that the business can actually use',excerpt:'A practical approach to connecting marketing assumptions to pipeline, revenue and capacity instead of producing a spreadsheet full of optimistic percentages.',date:'2026-09-15',readTime:'13 min read',category:'Commercial Growth',leadMagnet:'Marketing Strategy Canvas',tag:'Commercial Growth',content:[
{type:'p',text:'Marketing forecasts often fail because they look more precise than the underlying assumptions. A spreadsheet might show leads, conversion rates and revenue down to the nearest unit while nobody agrees on what those conversion rates actually mean.'},
{type:'p',text:'A useful forecast is different. It makes assumptions visible, connects marketing activity to commercial outcomes and gives leadership something to manage against.'},
{type:'h2',text:'Separate the forecast from the target'},
{type:'p',text:'A target is what the business wants to achieve. A forecast is what you currently believe will happen given the evidence and assumptions available.'},
{type:'p',text:'If you make the forecast equal to the target, the model stops being useful. It becomes a motivational document rather than an analytical one.'},
{type:'h2',text:'Build from the commercial outcome backwards'},
{type:'p',text:'Start with revenue or customers required. Then work backwards through average deal value or order value, win rate, qualified opportunities, conversion and the demand required to create those opportunities.'},
{type:'p',text:'The exact model depends on the business. The principle is that each layer should have a reason to exist and an assumption that can be challenged.'},
{type:'h2',text:'Make the assumptions explicit'},
{type:'ul',text:'Average order or contract value; sales cycle; conversion between stages; customer retention; capacity constraints; seasonality; channel contribution; ramp time; pricing changes.'},
{type:'p',text:'Then separate assumptions supported by historical evidence from assumptions that are simply plans. That distinction matters when leadership reviews the forecast.'},
{type:'h2',text:'Do not forecast every channel independently without considering overlap'},
{type:'p',text:'Customers rarely experience marketing as isolated channels. A person may see an ad, read an article, receive a referral and then speak to sales. If every channel receives full credit, the forecast can become inflated.'},
{type:'h2',text:'Capacity is part of the forecast'},
{type:'p',text:'Marketing can create more demand than sales, onboarding or operations can handle. That is not always a marketing success. If delivery capacity is constrained, the commercial plan has to account for it.'},
{type:'h2',text:'Use scenarios instead of pretending certainty'},
{type:'p',text:'A base case, upside case and downside case can be more useful than one highly precise number. Each scenario should change the assumptions that actually drive the outcome.'},
{type:'h2',text:'The forecast should change decisions'},
{type:'p',text:'If the forecast moves below plan, what happens? Do you change spend, proposition, sales capacity, target segment, pricing or timing? If nothing changes, the forecast is only reporting.'},
{type:'p',text:'The best commercial forecasts create a management conversation. They show where the business is depending on an assumption, where evidence is improving, and where a decision is required before the next period.'}]},

{slug:'when-marketing-is-not-the-problem',title:'When marketing is not the problem: five growth issues that look like marketing issues',excerpt:'Before changing the campaign, ask whether the real constraint is the product, proposition, sales process, pricing or customer experience.',date:'2026-09-15',readTime:'12 min read',category:'Growth Strategy',leadMagnet:'Marketing Strategy Canvas',tag:'Growth',content:[
{type:'p',text:'Marketing is an easy department to blame because it sits close to the customer. Sales are down, so change the ads. Leads are weak, so publish more content. Conversion is poor, so redesign the website.'},
{type:'p',text:'Sometimes those actions are right. Sometimes marketing is being asked to compensate for a problem it cannot solve.'},
{type:'h2',text:'1. The proposition is weak'},
{type:'p',text:'If customers do not see enough value in the offer, better distribution will not create sustained demand. Marketing can clarify value, but it cannot invent a reason to buy that the product does not deliver.'},
{type:'h2',text:'2. The product does not deliver the promised value'},
{type:'p',text:'Acquisition can be healthy while retention is poor because customers discover after purchase that the experience does not match the promise. The solution requires product or service improvement, not more retargeting.'},
{type:'h2',text:'3. Sales cannot convert the demand'},
{type:'p',text:'Marketing can create qualified opportunities that still go nowhere because the sales process is slow, inconsistent or poorly equipped. Look at follow-up time, qualification, objections, proposal quality and close rates.'},
{type:'h2',text:'4. Pricing or economics are wrong'},
{type:'p',text:'A campaign can perform exactly as designed while the customer economics remain unattractive. If acquisition cost, gross margin, retention and service cost do not support the model, improving CTR will not save the business.'},
{type:'h2',text:'5. The business has a capacity constraint'},
{type:'p',text:'Sometimes the reason growth is slowing is that delivery cannot keep up. More demand creates longer wait times, lower service quality and unhappy customers. Marketing needs to work with operations rather than simply trying to maximise volume.'},
{type:'h2',text:'Diagnose before you optimise'},
{type:'p',text:'A useful growth review should ask where the customer journey breaks and what evidence supports that diagnosis. Do not assume the answer is the channel with the most visible activity.'},
{type:'ul',text:'What changed? Where did the change first appear? Which customer segment is affected? What behaviour moved? What business constraint could explain it? What evidence would prove the hypothesis wrong?'},
{type:'h2',text:'The role of a senior marketer'},
{type:'p',text:'Senior marketing leadership is partly about knowing when not to market harder. Sometimes the most valuable recommendation is to change the offer, fix the onboarding, simplify the sales process, change the target customer or stop funding a segment that does not work.'},
{type:'p',text:'That is not stepping outside marketing. It is recognising that marketing exists to create business value, and business problems do not respect organisational boundaries.'}]},
];

export function getPost(slug:string){return posts.find(p=>p.slug===slug)}
