import type {Resource} from './resources';
const W=595,H=842,INK='0A1018',PEARL='ECEFF3',WHITE='F2F5F8',MUTE='94A1B1',BRASS='C69B4E',BRASS_LIGHT='EFD9A6';
function safe(v:string){return v.replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/[^\x20-\x7E]/g,'');}
function esc(v:string){return safe(v).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
function rgb(h:string){const n=parseInt(h,16);return `${((n>>16)&255)/255} ${((n>>8)&255)/255} ${(n&255)/255}`;}
function text(c:string[],x:number,y:number,s:number,v:string,color=WHITE,font='F1'){c.push(`BT /${font} ${s} Tf ${rgb(color)} rg ${x} ${y} Td (${esc(v)}) Tj ET`);}
function wrap(v:string,max:number){const out:string[]=[];let line='';for(const word of safe(v).split(/\s+/)){const next=line?`${line} ${word}`:word;if(next.length>max&&line){out.push(line);line=word}else line=next}if(line)out.push(line);return out;}

export function buildResourcePdf(resource:Resource){
 const pages:string[][]=[];
 const cover:string[]=[];cover.push(`q ${rgb(INK)} rg 0 0 ${W} ${H} re f Q`,`q ${rgb(BRASS)} rg 0 0 9 ${H} re f Q`);text(cover,54,760,11,'SIDDHARTH BHATTACHARJEE',BRASS,'F2');text(cover,54,704,42,resource.title,WHITE,'F2');let y=650;for(const line of wrap(resource.description,48)){text(cover,54,y,15,line,MUTE);y-=23}cover.push(`q ${rgb(BRASS_LIGHT)} rg 54 500 487 2 re f Q`);text(cover,54,458,12,'A PRACTICAL WORKING FRAMEWORK',BRASS,'F2');y=425;for(const line of wrap(resource.promise,58)){text(cover,54,y,19,line,WHITE,'F2');y-=28}text(cover,54,92,11,'siddharthbhattacharjee.in',MUTE);text(cover,54,70,10,'email@siddharthbhattacharjee.in  |  +91 70931 42389',MUTE);pages.push(cover);
 let current:string[]=[];let yPos=760;const start=()=>{current=[`q ${rgb(PEARL)} rg 0 0 ${W} ${H} re f Q`,`q ${rgb(BRASS)} rg 0 ${H-9} ${W} 9 re f Q`];text(current,48,800,9,'SIDDHARTH BHATTACHARJEE  /  '+resource.category,BRASS,'F2');yPos=758};const finish=()=>{text(current,48,30,8,'siddharthbhattacharjee.in','5D6875');text(current,445,30,8,'Consulting  |  Strategy  |  Growth','5D6875');pages.push(current)};start();
 for(const section of resource.sections){if(yPos<150){finish();start()}for(const line of wrap(section.heading,48)){text(current,48,yPos,19,line,INK,'F2');yPos-=23}yPos-=5;for(const item of section.items){const lines=wrap(item,76);const needed=lines.length*17+13;if(yPos-needed<55){finish();start()}current.push(`q ${rgb(BRASS)} rg 48 ${yPos+2} 4 4 re f Q`);let yy=yPos;for(const line of lines){text(current,64,yy,11.5,line,'25303A');yy-=17}yPos=yy-13}yPos-=13}finish();
 const final:string[]=[];final.push(`q ${rgb(INK)} rg 0 0 ${W} ${H} re f Q`);text(final,54,760,11,'THE NEXT QUESTION',BRASS,'F2');text(final,54,700,34,'What would this look like',WHITE,'F2');text(final,54,660,34,'inside your business?',WHITE,'F2');let fy=602;for(const line of wrap('A framework is useful. Applying it to a real business is where the difficult decisions begin.',54)){text(final,54,fy,15,line,MUTE);fy-=23}final.push(`q ${rgb(BRASS)} rg 54 500 487 1 re f Q`);text(final,54,468,12,'WORK WITH SIDDHARTH',BRASS,'F2');fy=432;for(const line of wrap('If you are dealing with a growth, positioning, demand, product marketing, CRM or go-to-market problem, send me a short brief.',56)){text(final,54,fy,15,line,WHITE);fy-=23}text(final,54,300,13,'email@siddharthbhattacharjee.in',BRASS_LIGHT,'F2');text(final,54,274,13,'+91 70931 42389',BRASS_LIGHT,'F2');text(final,54,248,13,'siddharthbhattacharjee.in',BRASS_LIGHT,'F2');pages.push(final);
 const streams=pages.map(p=>p.join('\n'));let pdf='%PDF-1.4\n';const offsets:number[]=[0];const add=(id:number,body:string)=>{offsets[id]=Buffer.byteLength(pdf,'latin1');pdf+=`${id} 0 obj\n${body}\nendobj\n`};
 add(1,'<< /Type /Catalog /Pages 2 0 R >>');add(2,`<< /Type /Pages /Kids [${pages.map((_,i)=>`${3+i*2} 0 R`).join(' ')}] /Count ${pages.length} >>`);
 let id=3;for(const stream of streams){add(id,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents ${id+1} 0 R >>`);offsets[id+1]=Buffer.byteLength(pdf,'latin1');pdf+=`${id+1} 0 obj\n<< /Length ${Buffer.byteLength(stream,'latin1')} >>\nstream\n${stream}\nendstream\nendobj\n`;id+=2}
 const fontRegular=id,fontBold=id+1;add(fontRegular,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');add(fontBold,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
 const xref=Buffer.byteLength(pdf,'latin1');pdf+=`xref\n0 ${fontBold+1}\n0000000000 65535 f \n`;for(let i=1;i<=fontBold;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${fontBold+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf,'latin1');
}
