import Link from 'next/link';
import { ArrowUpRight, Download } from 'lucide-react';
import NewsletterForm from '../../../components/NewsletterForm';
const data:Record<string,{title:string;desc:string;steps:string[]}>={
'marketing-strategy-canvas':{title:'Marketing Strategy Canvas',desc:'A one-page framework for turning a business problem into a set of marketing choices.',steps:['What business outcome needs to change?','Who is the highest-value customer?','What problem or job are they trying to solve?','Why should they choose you over the alternatives?','Which acquisition and retention levers matter most?','What will you measure in the next 90 days?']},
'landing-page-checklist':{title:'Landing Page Checklist',desc:'Twelve practical checks for a page that needs to convert more visitors into enquiries or customers.',steps:['Is the promise obvious in the first few seconds?','Does the headline match the traffic source?','Is the audience clear?','Is there enough proof?','Are objections answered?','Is the CTA specific and visible?']},
'gtm-template':{title:'GTM Planning Template',desc:'A simple structure for planning a product or service launch.',steps:['Define the launch objective.','Choose the priority audience.','Write the value proposition.','Define positioning and message.','Plan launch channels and sequencing.','Define adoption and success metrics.']},
'brand-positioning-worksheet':{title:'Brand Positioning Worksheet',desc:'A practical worksheet for finding a clearer reason for customers to choose you.',steps:['Who is the priority customer?','What alternatives do they consider?','What do those alternatives own in the customer’s mind?','What can you credibly own?','What proof makes the position believable?','How should the position change your marketing?']},
'b2b-marketing-canvas':{title:'B2B Marketing Canvas',desc:'Map the parts of a B2B demand-generation system before choosing more channels.',steps:['Define the best-fit account.','Identify the buying problem.','Clarify the business value.','Map demand sources.','Design content and sales handoffs.','Choose lead and revenue metrics.']},
'lifecycle-marketing-map':{title:'Lifecycle Marketing Map',desc:'A simple way to see where customers need different marketing interventions.',steps:['Acquisition','Activation','First value','Repeat behaviour','Retention','Reactivation']},
};
export async function generateStaticParams(){return Object.keys(data).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return {title:`${data[slug]?.title||'Marketing Resource'} | Siddharth Bhattacharjee`,description:data[slug]?.desc};}
export default async function Resource({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const r=data[slug];if(!r)return null;return <main><article className="container resource-detail"><div className="eyebrow">Free resource</div><h1 className="display">{r.title}</h1><p className="article-lead">{r.desc}</p><div className="resource-download"><Download size={20}/><div><strong>Use this as a working document.</strong><span>The first version is deliberately simple. Copy it into your own notes or document and adapt it to your business.</span></div></div><div className="resource-email"><div><div className="num">Get the resource + future frameworks</div><h2>Send it to my inbox.</h2><p>I’ll also send the occasional useful marketing idea. You can unsubscribe any time.</p></div><NewsletterForm source={slug} tag="Resource" compact successHref={`/resources/${slug}.pdf`}/></div><div className="resource-steps">{r.steps.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div><div className="resource-cta"><h2>Want an experienced marketer to work through this with you?</h2><Link className="button" href="/#booking">Book a conversation <ArrowUpRight size={16}/></Link></div></article></main>}
