import Link from 'next/link';
import {ArrowUpRight,BookOpen,ShoppingCart} from 'lucide-react';
import {BOOK} from '../../lib/links';

export const metadata={title:'The Sovereign Brand | Building Brands in the Age of AI',description:'The Sovereign Brand is a practical operating model for marketers who want to use AI without outsourcing judgement. Explore the ideas, frameworks and 90-day plan in Siddharth Bhattacharjee’s book.',keywords:['The Sovereign Brand','AI marketing book','AI marketing strategy','AI marketing operating model','marketing in the age of AI','Siddharth Bhattacharjee']};

export default function BookPage(){
 const bookSchema={'@context':'https://schema.org','@type':'Book','name':'The Sovereign Brand: Building Brands in the Age of AI','author':{'@type':'Person','name':'Siddharth Bhattacharjee','url':'https://siddharthbhattacharjee.in'},'bookFormat':'https://schema.org/EBook','description':'A practical operating model for marketers who want to use AI without outsourcing judgement.','url':'https://siddharthbhattacharjee.in/book'};
 return <main className="surface-pearl book-page">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(bookSchema)}} />
  <section className="book-hero"><div className="container book-hero-grid"><div><p className="label">The book · Volume I</p><h1 className="display h-xl">The Sovereign Brand</h1><p className="book-kicker">Building Brands in the Age of AI</p><p className="book-lead">A practical operating model for marketers who want to use AI without outsourcing judgement.</p><div className="book-actions"><a className="button" href={BOOK.gumroad} target="_blank" rel="noreferrer"><BookOpen size={16}/> Get the e-book <ArrowUpRight size={15}/></a><a className="button alt" href={BOOK.amazon} target="_blank" rel="noreferrer"><ShoppingCart size={16}/> Amazon Kindle <ArrowUpRight size={15}/></a></div><p className="book-micro">Read it if you want to understand the operating model behind my approach to modern marketing.</p></div><div className="book-visual"><div className="book-cover-real"><span>Siddharth Bhattacharjee</span><div><strong>THE<br/>SOVEREIGN<br/>BRAND</strong><i>Building Brands in the Age of AI</i></div><small>VOLUME I</small></div></div></div></section>

  <section className="book-intro"><div className="container book-two-col"><div><p className="eyebrow">Why this book exists</p><h2 className="display h-lg">AI made production cheaper. It did not make judgement less important.</h2></div><div><p>The marketing industry spent the first years of generative AI asking how quickly machines could make things. The more consequential question is how marketing organisations should think and operate when intelligence becomes abundant.</p><p><i>The Sovereign Brand</i> looks at systems, customer understanding, brand knowledge, decisioning, content, trust, organisation design and the economics of recovered human attention. It is deliberately a marketing book, not a technology manual.</p><p>The principles are designed to survive changes in models and tools. The objective is a marketing organisation that can use increasingly capable systems without becoming dependent on their defaults.</p></div></div></section>

  <section className="surface-ink book-framework"><div className="container"><div className="section-head section-head--split"><div><p className="label">The central idea</p><h2 className="display h-lg">Build the system around the model.</h2></div><p>A good model with weak context produces generic work. Strong data without an operating model produces dashboards. The advantage comes from connecting signals, judgement, execution and learning.</p></div><div className="book-loop"><span>Sense</span><b>→</b><span>Interpret</span><b>→</b><span>Decide</span><b>→</b><span>Create</span><b>→</b><span>Deploy</span><b>→</b><span>Measure</span><b>→</b><span>Learn</span></div><div className="book-stack"><div><strong>01 · Sensory</strong><h3>What is happening?</h3><p>Customer conversations, search behaviour, reviews, sales feedback, campaign performance, competitor movements and product usage.</p></div><div><strong>02 · Cognition</strong><h3>What does it mean?</h3><p>Brand Soul, customer truth, product truth, evidence, competitive context and decision rules.</p></div><div><strong>03 · Action</strong><h3>What should we do?</h3><p>Content, campaigns, experiments, lifecycle communication, reporting and operational actions.</p></div></div></div></section>

  <section className="book-chapters"><div className="container"><p className="eyebrow">Inside Volume I</p><h2 className="display h-lg">15 chapters about what changes when intelligence becomes abundant.</h2><div className="chapter-grid">{['Marketing Changed Before Most Marketers Noticed','The Customer No Longer Follows Your Funnel','From Campaigns to Systems','The Sensory Layer: Your Brand Needs Ears','The Cognition Layer: Build a Brand Soul','The Action Layer: What Should AI Actually Do?','Personalisation: From Segments to Decisions','Content Becomes Cheap. Attention Does Not.','Search Is Becoming an Answer','Data Is the New Infrastructure','Trust Becomes a Competitive Advantage','The Human Advantage','The New Marketing Team','The Economics of AI Marketing','The 90-Day Sovereign Brand Plan'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3></div>)}</div></div></section>

  <section className="book-practical"><div className="container book-two-col"><div><p className="eyebrow">The practical part</p><h2 className="display h-lg">It is meant to be used, not just read.</h2></div><div className="book-tools"><div><strong>Sovereign Marketing Operating Model</strong><p>Seven disciplines: Sense, Interpret, Decide, Create, Deploy, Measure and Learn.</p></div><div><strong>AI Marketing Use-Case Matrix</strong><p>A decision model for what to automate, augment, delegate with controls or keep human-led.</p></div><div><strong>Brand Soul Starter Template</strong><p>A structured way to capture identity, customer truth, product truth, decision logic and expression.</p></div><div><strong>20 Questions Every Marketing Leader Should Ask</strong><p>A leadership checklist for examining how the marketing organisation is changing.</p></div></div></div></section>

  <section className="surface-pearl book-plan"><div className="container"><div className="book-plan-head"><p className="eyebrow">The 90-day plan</p><h2 className="display h-lg">Do not transform the whole marketing function. Build one working loop, prove it, then expand.</h2></div><div className="plan-grid"><div><span>Days 1-15</span><h3>Audit</h3><p>Map one important workflow, its inputs, decisions, outputs, owners, handoffs and feedback. Establish the baseline.</p></div><div><span>Days 16-30</span><h3>Build Brand Soul</h3><p>Structure customer truth, product truth, identity, decision logic and expression. Separate approved truth from historical material.</p></div><div><span>Days 31-45</span><h3>Build one workflow</h3><p>Choose a workflow that can demonstrate value within a month and define exactly what the human and system each do.</p></div><div><span>Days 46-60</span><h3>Improve creation</h3><p>Start with source material, then create the format. Build reusable context, examples and quality checks.</p></div><div><span>Days 61-75</span><h3>Deploy and measure</h3><p>Put the workflow into the real environment, connect data, establish owners and compare economics with the baseline.</p></div><div><span>Days 76-90</span><h3>Close the loop</h3><p>Update knowledge, workflow and decision rules from what happened, then choose the next workflow.</p></div></div></div></section>

  <section className="surface-ink book-close"><div className="container book-close-inner"><div><p className="label">The Sovereign Brand</p><h2 className="display h-lg">Not an AI brand. A brand with enough intelligence, memory and judgement to use AI without losing itself.</h2><p>The book is the clearest way to see the thinking behind my work. Read it, use the frameworks, and if the ideas expose a bigger problem in your business, we can talk about it.</p></div><div className="book-actions"><a className="button" href={BOOK.gumroad} target="_blank" rel="noreferrer"><BookOpen size={16}/> Get the e-book <ArrowUpRight size={15}/></a><a className="button alt" href={BOOK.amazon} target="_blank" rel="noreferrer"><ShoppingCart size={16}/> Buy on Amazon <ArrowUpRight size={15}/></a><Link className="button alt" href="/#booking">Talk about your business <ArrowUpRight size={15}/></Link></div></div></section>
 </main>
}
