'use client';
import { useState } from 'react';
import { ArrowUpRight, ChevronDown } from 'lucide-react';
const problems=[
{id:'01',problem:'We get traffic, but not enough enquiries or sales.',diagnosis:'I start at the conversion point, not the ad account. I look at the offer, message match, proof, friction, CTA and the quality of traffic coming in.',approach:['Review the customer journey','Audit the landing page and offer','Find the biggest conversion leaks'],deliverable:'A prioritised conversion roadmap',cta:'Get a conversion review'},
{id:'02',problem:'We need a marketing strategy, but everything feels scattered.',diagnosis:'I work backwards from the commercial goal, priority customer and competitive context, then decide what marketing should actually do.',approach:['Clarify the commercial goal','Choose priority audiences','Set marketing priorities'],deliverable:'A practical marketing strategy and 90-day roadmap',cta:'Discuss my strategy'},
{id:'03',problem:'Our leads are weak, expensive or too dependent on referrals.',diagnosis:'For B2B, I look at positioning, demand creation, acquisition, content, conversion and lead quality as one system.',approach:['Define best-fit customer segments','Pressure-test the proposition','Map demand and acquisition'],deliverable:'A B2B demand and acquisition plan',cta:'Talk about B2B growth'},
{id:'04',problem:'We launched a product, but adoption is slower than expected.',diagnosis:'I connect product value, positioning, launch communication, onboarding and lifecycle messaging to find where adoption is breaking.',approach:['Clarify the job the product solves','Fix product messaging','Design activation and retention journeys'],deliverable:'A product marketing and adoption plan',cta:'Review the launch'},
{id:'05',problem:'People understand what we sell, but not why they should choose us.',diagnosis:'That is usually a positioning problem before it is a creative problem. I look at alternatives, customer value, proof and the reason to believe.',approach:['Map alternatives','Find the strongest customer value','Build positioning and messaging'],deliverable:'A positioning and messaging framework',cta:'Review our positioning'},
{id:'06',problem:'The marketing team is busy, but growth still feels flat.',diagnosis:'I look for the gap between activity and outcomes: too many priorities, weak measurement, channel dependence or a strategy that no longer fits the business.',approach:['Audit current priorities','Find the few metrics that matter','Build a focused growth backlog'],deliverable:'A prioritised marketing operating plan',cta:'Get an outside perspective'}];
export default function Problems(){const[open,setOpen]=useState('01');return <div className="problem-list">{problems.map(p=><article className={`problem-item ${open===p.id?'is-open':''}`} key={p.id}><button className="problem-trigger" onClick={()=>setOpen(open===p.id?'':p.id)} aria-expanded={open===p.id}><span className="problem-number">{p.id}</span><span className="problem-title">{p.problem}</span><ChevronDown size={20}/></button>{open===p.id&&<div className="problem-detail"><div className="problem-main"><div className="num">How I would approach it</div><p>{p.diagnosis}</p></div><div><div className="num">First steps</div><ul>{p.approach.map(x=><li key={x}>{x}</li>)}</ul></div><div className="problem-output"><div className="num">Likely output</div><strong>{p.deliverable}</strong><a href="#booking">{p.cta} <ArrowUpRight size={15}/></a></div></div>}</article>)}</div>}
